glasskube/glasskube

- .goreleaser.yaml
- README.md
- website/docs/04_guides/01_cert-manager.mdx
- website/docs/index.md
- website/src/pages/index.tsx
For this change the repo github.com/glasskube/homebrew-glasskube was renamed to  github.com/glasskube/homebrew-tap
> ci: rename homebrew tap repository and install docs

- README.md
This PR replaces the Asciinema link in our readme with an embedded GIF. 
Preview: https://github.com/glasskube/glasskube/blob/kosmoz/readme-gif/README.md
Note, that there is currently no direct way to use asciinema recordings as GIFs or videos. 
There is only a [tool that does the conversion locally](https://github.com/asciinema/agg), but it has it's limitations, like not supporting all characters.
I think the Asciinema preview looks better. I also tried converting the GIF to a video but that looked truly terrible.
> docs: change asciinema link to gif

- config/dependencies/flux/helm-controller.yaml
- config/dependencies/flux/source-controller.yaml
Closes #148 
This PR removes the …cluster.local part from the domains in flux manifests, so it should also work on clusters where this name is different.
> fix(package-operator): remove cluster.local dns suffix from flux manifests

- config/rbac/kustomization.yaml
- config/rbac/role_binding.yaml
The Package Operator needs the cluster-admin ClusterRole.
This might seem excessive, but I think in the end it is required, since packages might need to create all kinds of resources…
> fix(package-operator): add missing rbac permissions

- website/src/partials/_install.mdx
This should improve compatibility with different renderers, as HTML comments are not always supported.
After merging, we need to monitor if release-please still picks these up, but I think it should.
The relevant documentation can be found [here](https://github.com/googleapis/release-please/blob/main/docs/customizing.md#updating-arbitrary-files).
> docs: change release-please annotations to mdx comments

- CONTRIBUTING.md
- cmd/glasskube/cmd/serve.go
- internal/web/server.go
Closes #83
- `glasskube serve` generally listens on port `8580`. This PR ensures to add a new flag `--port` to the `glassdoor serve` command so that the webserver can be opened on any port specified via CLI Flag.
- Updated the `contributing.md` file to mention developing the glasskube binary locally. 
- Fix minor typos in the codebase.
> feat: add `port` flag to `glasskube serve`

- .github/workflows/commit-lint.yaml
commit lint has a default ignore list:
https://github.com/conventional-changelog/commitlint/blob/master/%40commitlint/is-ignored/src/defaults.ts
> ci: disable commit lint default ignores

- .goreleaser.yaml
We should not publish prereleases in this way.
> build: prevent uploading prereleases to brew tap

- website/src/partials/_install.mdx
Executables will still be downloaded from GitHub release assets This commit should also solve the release-please problem of having multiple version replacements in one line (googleapis/release-please#2137).
> docs: use a custom domain for binary downloads

- .goreleaser.yaml
`changelog.skip` is deprecated, this showed up in the logs of our release workflow.
Ref: https://goreleaser.com/deprecations/#changelogskip
> build: change deprecated goreleaser config property

- .github/workflows/release.yaml
- .goreleaser.yaml
Closes #237 
I adjusted the goreleaser configuration as well as the action definitions to build multiarch images, at the moment for `linux/amd64` and `linux/arm64`.
The resulting image runs on Apple Silicon architectures, I double-checked.
If you want to see the updated action in action (pun intended), [have a look at my fork](https://github.com/mocdaniel/glasskube/actions/runs/7857834325/job/21442133990), and/or pull the resulting images from [here](https://github.com/users/mocdaniel/packages/container/package/package-operator).
> fix(action): build package-operator image for amd64, arm64

- api/v1alpha1/package_manifest.go
- config/crd/bases/packages.glasskube.dev_packageinfos.yaml
- pkg/open/open.go
- schema/package-manifest/schema.json
This PR adds two optional properties to the PackageEntrypoint type: `Scheme` and `LocalPort`.
This is needed to fix the entrypoint for the kubernetes-dashboard.
Once this PR has been approved and merged, the kubernetes-dashboard package must be updated to use the new properties.
> feat: add Scheme, LocalPort to PackageEntrypoint

- renovate.json
Renovate does not do this by default.
Relevant documentation: https://docs.renovatebot.com/golang/#module-tidying
> chore: make renovate run "go mod tidy"

- .github/workflows/schema.yaml
- Makefile
- internal/cmd/schema-gen/main.go
- test/package-manifest/example.yaml
- website/static/schemas/v1/package-manifest.json
Closes #258 
With this PR, our schema files no longer use $ref, since it is strictly speaking not standards compliant and not very well supported by some tooling. 
The schema files are now written to website/static, which makes them available via our website. 
The $id of the schema reflects this change.
Once this is merged, we can remove the schema files from the packages repo and update all packages to reference the new schema location
> chore: change schema to not use $ref and move to website

- cmd/glasskube/cmd/version.go
- go.mod
- go.sum
Closes #254 
Added a version command which prints the version of glasskube and package-operator.
```
$ glasskube version
glasskube: v0.0.3
package-operator: v0.0.2 
```
If no deployments are found under glasskube-system namespace it prints
```
$ glasskube version
glasskube: v0.0.3
✗ no deployments found in the glasskube-system namespace
```
> feat: add version command

- cmd/package-operator/main.go
- internal/controller/owners/owners.go
- internal/controller/package_controller.go
- internal/controller/packageinfo_controller.go
- internal/manifest/adapter.go
- internal/manifest/helm/flux/adapter.go
- pkg/client/package.go
- pkg/uninstall/uninstall.go
With this PR, foreground deletion is enabled when uninstalling a Package.
Note: The uninstall cmd still doesn't wait for the resource to be deleted, but the functionality can be tested using `kubectl delete --cascade=foreground pkg <package-name>`.
* Relevant documentation:
* https://kubernetes.io/docs/concepts/architecture/garbage-collection/#foreground-deletion
* https://kubernetes.io/docs/tasks/administer-cluster/use-cascading-deletion/#use-foreground-cascading-deletion
* This unblocks #133 and #168
> feat: add blocking owner deletion 

- pkg/describe/describe.go
- pkg/manifest/manifest.go
If a package has a `.Spec.Version`, the name of the PackageInfo is no longer the same as the package. In such a case, the details page is currently broken. This PR fixes that.
> fix(ui): use real PackageInfo name when getting installed manifest

- cmd/glasskube/cmd/list.go
- cmd/glasskube/cmd/uninstall.go
- internal/cliutils/table.go
- internal/config/config.go
- internal/repo/types.go
- internal/web/components/pkg_overview_btn/controller.go
- internal/web/templates/pages/packages.html
- pkg/list/list.go
- website/static/schemas/v1/index.json
Closes #200 
This PR adds two new columns to the output of `glasskube list`:
* VERSION: shows the installed version plus the spec version and/or available version (from the registry) if they are different
* LATEST VERSION: shows the latest version (from the registry) - Disabled by default
`glasskube list` now has two additional flags: 
* `--show-latest`: enables the LATEST VERSION column (see above)
* `--more` or `-m`: equivalent to `--show-description --show-latest`
I also took the liberty and moved all command specific config variables to their respective command files, as there is no need for a global variable for those.
Some parts of the version column rely on a `latestVersion` being present for the package in the package index (see updated schema file). This is currently not the case …
> feat(cli): add showing package version in list cmd (#200)

- cmd/glasskube/cmd/install.go
- internal/web/server.go
- pkg/client/package.go
- pkg/install/install.go
- website/docs/index.md
Closes #203  
This PR adds two additional flags to the `glasskube install` command:
* `--version`: install a specific version of a package
* `--enable-auto-updates`: always keep this package at the latest version
If neither is specified, the user is asked if automatic updates should be enabled. 
If they answer "no", the latest version of the package is fetched and used for installation.
Web UI is still TODO.
~Docs will be updated after review.~ Docs updated
> feat(cli): add installing specific package version (#203)

- internal/repo/repo.go
Our repository currently does not handle URLs correctly, "+" needs to be escaped, even though it is technically allowed in URL path segments. With this PR, all (non-static) path segments are path-escaped with the addition of "+" being escaped as well.
Relevant documentation:
* https://datatracker.ietf.org/doc/html/rfc3986#section-2.2 (sub-delims)
* https://datatracker.ietf.org/doc/html/rfc3986#section-3.3 (pchar)
> fix: add path escaping repository urls

- cmd/glasskube/cmd/root.go
- cmd/glasskube/main.go
- internal/cliutils/checkforupdate.go
- internal/config/config.go
This PR includes several changes to the already existing update check feature:
* It is now less obtrusive and more similar to our other CLI messages
* There is a new (global) `--skip-update-check` flag that does what it says it does
* `--skip-update-check` is `true` by default in development builds (this can be overridden by using `--skip-update-check=false`
I did not update the documentation, I'm not sure if it's even necessary to document the new flag outside of the `help` command…
> feat(cli): change update message to be less obtrusive

- cmd/glasskube/cmd/list.go
- internal/web/server.go
- pkg/list/list.go
- website/docs/index.md
Closes #201 
This PR adds a a new flag `--outdated` to the list subcommand. This flag is false by default. If it is set to true, the output is restricted to those packages with an outdated version.
I also refactored the ListOptions type from an int type to a struct because I think it is much more convenient and less error prone.
> feat(cli): add outdated flag for list cmd (#201)

- internal/web/server.go
- internal/web/templates/layout/base.html
- internal/web/templates/pages/packages.html
Closes #263 
With this PR, the currentContext from the selected kubeconfig is always shown in the navbar of the UI:
Placement/Visuals are up for discussion.
> feat(ui): add current context in navbar (#263)

- package-lock.json
Previously the build failed, because the package-lock.json file directed the new @glasskube/theme dependency to the "private" github package instead of the npmjs package.
The change has been done by removing the private auth token from my local .npmrc file, removing node_modules and reinstall dependencies with `npm i` – npm then uses the npmjs package instead of the github one. Probably there would have been a better way but this seems to work. However, if one changes back to have the auth token in the .npmrc file, the Github registry is used preferrably by npm.
For the future, I think it would be better to not publish the theme to the github registry at all to avoid this.
Related #313
> build: use glasskube/theme dependency from npmjs

- .github/workflows/build.yaml
This PR adds attaching the built binaries as artifacts to the GitHub workflow run
> ci: add upload-artifact step for build action

- cmd/package-operator/main.go
- internal/controller/owners/utils/owned_resources.go
- internal/controller/owners/utils/owners.go
- internal/controller/package_controller.go
- internal/controller/requeue/requeue.go
- internal/controller/utils.go
- internal/manifest/helm/flux/adapter.go
- internal/manifest/plain/adapter.go
- internal/manifest/result/result.go
Closes #328 
This PR changes the way the package controller operators pretty significantly: Previously, we updated the package status intermittently in some cases, but deferred updates to the end, risking missing data in case of an error, in others. Both approaches are not ideal were used inconsistently. 
With this change, the package status is only updated once per reconciliation. The update is performed as the last step, whether an error has occurred or not. This means that we no longer lose track of owned resources that were created before an error occurred. 
HelmReleases and HelmRepositories created by the FluxHelmAdapter are now also tracked as owned resources.
It is now possible to support both helm and manifests in a package. This allows package authors to include additional …
> feat(package-operator): add handling of packages with helm and manifests

- api/v1alpha1/package_manifest.go
- config/crd/bases/packages.glasskube.dev_packageinfos.yaml
- internal/manifest/plain/adapter.go
- website/static/schemas/v1/package-manifest.json
Closes #333 
This PR adds a `defaultNamespace` property to plain manifests. 
If a plain mainfest includes resources of a namespaced kind that do not have a namespace set, they will be created in the default namespace. 
Required for https://github.com/glasskube/packages/pull/41
> feat(package-operator): add default namespace handling for plain manifests

- .goreleaser.yaml
Until now, our release archives and installers included both the glasskube CLI and package-operator binaries. With this PR, only the glasskube CLI is included.
To test: `goreleaser release --snapshot --clean` (this will skip all publishing steps)
> build: change goreleaser config to only include cli in artifacts

- cmd/glasskube/cmd/bootstrap.go
- cmd/glasskube/cmd/describe.go
- cmd/glasskube/cmd/install.go
- cmd/glasskube/cmd/list.go
- cmd/glasskube/cmd/open.go
- cmd/glasskube/cmd/uninstall.go
- cmd/glasskube/cmd/update.go
- cmd/glasskube/cmd/version.go
- internal/cliutils/setupclientcontext.go
- internal/cliutils/versionutil.go
Closes # 
This PR adds a feature to detect version mismatch between PackageOperator & CLI and notifies the user.
**Changes Made:**
Moved GetPackageOperatorVersion() to `glasskube/internal/cliutils/versionutil.go`
added CheckPackageOperatorVersion() function
Added `--skip-update-check ` flag support to skip update checks
```
$ ./glasskube list --skip-update-check=false
❗ Glasskube PackageOperator needs to be updated: 0.0.4 -> dev
💡 Please run `glasskube bootstrap` again to update Glasskube PackageOperator
NAME                  STATUS         VERSION
argo-cd               Not installed    
cert-manager          Not installed    
cyclops               Not installed    
ingress-nginx         Not installed    
keptn                 Not installed    
kubernetes-dashboard  Not installed    
``` …
> feat: add version mismatch detection for PackageOperator

- internal/cliutils/checkforupdate.go
- internal/semver/compare.go
- internal/semver/compare_test.go
- internal/semver/semver_suite_test.go
- pkg/update/update.go
Closes #397 
With this PR, the build metadata field of the semver is also considered when we check if a version can be upgraded. For this I defined the following rules:
* installed and latest have same metadata (empty or not) -> false
* installed has metadata and latest has no metadata -> false
* installed has no metadata and latest has metadata -> true
* installed and latest have a number as metadata -> installed < latest
* installed and latest have metadata but either is not a number -> installed != latest
Whether we want to allow metadata values that are not integers is of course up for debate, but at least the behavior in such a case is now defined.
> fix: consider semver metadata when comparing installed vs latest version (#397)

- config/webhook-cert/rbac.yaml
This PR adds the permission to create secrets in the glasskube-system namespace for the webhook cert manager.
> fix(package-operator): add missing permissions for webhook-cert

- config/manager/kustomization.yaml
The image declaration has been moved to `config/default`, but it is still in ` config/manager`, probably due to an error when resolving merge conflicts.
> chore: remove redundant image in manager kustomization

- internal/web/components/pkg_detail_btns/controller.go
- internal/web/components/pkg_overview_btn/controller.go
- internal/web/templates/components/pkg-detail-btns.html
- internal/web/templates/components/pkg-overview-btn.html
Swapping the overview and detail buttons also works without the swap attribute, this seems to be considered by default when sending its sent via websocket by htmx.
> chore(ui): remove unnecessary htmx swap attributes

- internal/web/components/alert/controller.go
- internal/web/server.go
- internal/web/templates.go
- internal/web/templates/components/alert.html
- internal/web/templates/components/pkg-overview-btn.html
- internal/web/templates/layout/base.html
- internal/web/templates/pages/package.html
- web/index.js
Accidently messed up #420 
Made error handling a bit more reusable by introducing a util function on the server, which renders an html template. This template is sent together with two HTMX response headers.
This should be re-usable everywhere in the application because the response headers overwrite any client-side `hx-select` / `hx-swap` attributes in case of an error. 
The htmx extension [response-targets](https://htmx.org/extensions/response-targets/) does the swapping clientside. 
There is also the possibility now to show server-side errors on a page template, e.g. when loading the packages page errors for some reason.
> feat(ui): introduce global error handling

- go.mod
- internal/web/server.go
- internal/web/templates.go
Closes #170 
With this PR, the web server selects a different FS depending on whether glasskube is running in development mode. In development mode, an os.DirFS is used and a fsnotify.Watcher is created to parse the templates again after file changes. In production mode, an embed.FS (as before).
Additionally, template parsing has been deferred to the server Start function which might make other commands a little more performant.
> chore(ui): add reloading templates after changes in dev mode (#170)

- internal/web/templates/components/pkg-overview-btn.html
- internal/web/templates/pages/packages.html
I noticed that only the texts and buttons on the package list are actual links. With this PR, the entire card surface becomes clickable.
> fix(ui): make the whole card on package list clickable

- internal/web/server.go
- internal/web/templates/components/pkg-update-modal.html
- internal/web/templates/pages/package.html
- pkg/describe/describe.go
- pkg/manifest/manifest.go
Closes #382
We make use of the `Hx-Trigger` response header at the `install`, `update` and `uninstall` endpoints and use this trigger on the package detail page to reload its content.
> feat(ui): trigger refreshing package detail page (#382)

- pkg/list/list.go
Closes #419 
See issue details for info on the bug
> fix(ui, cli): prevent a panic if a package has no OwnedPackageInfo (#419)

- internal/web/server.go
> fix(ui): parse templates before starting informer to avoid panic

- website/src/partials/_install.mdx
Added instructions on how to install Glasskube via nix, this works for Linux and MacOS (and maybe Windows), so I added it to the Readme directly as opposed to the installation methods web page.
This PR is still marked as a draft, because the Nixpkgs PR has not been merged yet, please leave a 👍 to increase the chances of it being merged quicker: https://github.com/NixOS/nixpkgs/pull/285513
> docs: add instructions for installation via nix

- internal/clientutils/resources.go
- internal/manifest/plain/adapter.go
- pkg/bootstrap/bootstrap.go
Closes #464  
This PR fixes several problems of the BootstrapClient:
- not handling `nil` correctly when checking deployment status (which lead to the bug in #464)
- it creates and checks resources in order, which is now sped up significantly by applying all, then checking them in sequence
- ignoring apply error
- using timer instead of ticker when checking deployment status
In addition to the above, bootstrap now also prints how long it took :slightly_smiling_face:
> fix(cli, ui): bootstrap handles nil values in `checkWorkloadReady` and major speedup

- cmd/glasskube/cmd/list.go
Closes #441
Fixes #441
`glasskube ls` should not show latest available version if installed version is newer than latest version
This is how the terminal looks like now.
Notice here the argo-cd package is installed on the pre-release version.
```
PS H:\glasskube> .\main.exe ls   
NAME                  STATUS         VERSION                                  AUTO-UPDATE
argo-cd               Ready          v2.10.5+1
cert-manager          Ready          v1.14.2+1
cyclops               Not installed
ingress-nginx         Not installed
keptn                 Ready          v2.0.0-rc.1+1 (v2.0.0-rc.2+1 available)
kubernetes-dashboard  Ready          v2.7.0+1 (v2.7.0+2 available)
```
> feat(cli): should not show latest version if installed version is newer

- internal/webhook/package_validator.go
Currently, the validating webhook erroneously skips validation for updates if the `.Spec.PackageInfo` did not change. This is no longer correct since we now have more spec items than that.
> fix(package-operator): don't skip update validation if values changed

- internal/manifestvalues/resolver.go
Currently, if an error is encountered during config value resolution, it is returned. With this change, all errors are resolved and a multi error is returned so that a user can always know all the values that can not be resolved
This came up in https://github.com/glasskube/glasskube/pull/479#discussion_r1560936268
> fix: always try to resolve all values to improve error message

- internal/web/templates/components/pkg-overview-btn.html
When clicking the Install button from the packages overview page, then installing the opened package, and navigating back to the overview page with the browser back button, the page was not refreshed correctly. Cause was that the link to the package detail page did not have the `hx-boost=true` flag, which made it load the complete page. It seems that then the `htmx:historyRestore` used to reload the page contents when going back, does not work correctly.
> fix(ui): add hx-boost to fix inconsistent browser back/forth

- internal/controller/packageinfo_controller.go
This PR fixes a bug that exists since a long time. If there is an error during the PackageInfo reconciliation, the operator could enter a state where it would repeatedly reconcile the related Package and PackageInfo over and over again. By not setting the "updating manifest" condition on the PackageInfo, this no longer happens, because in case the error happens again, no resource update is needed. Normal exponential backoff still applies.
> fix(package-operator): prevent reconcile loop on packageinfo error

- internal/web/server.go
- pkg/client/package_cache.go
- pkg/client/packageinfo_cache.go
This PR fixes a performance issue which occurs when at least 4 packages are installed in a cluster + the user switches back and forth between package detail pages very quickly. The cause of this was that the used package client was not actually the cached one, because of the incorrect initialization.
> fix(ui): restructure server initializations

- README.md
- cmd/glasskube/cmd/root.go
- pkg/bootstrap/bootstrap.go
- website/blog/2024-02-01-technical-preview/index.mdx
- website/blog/2024-02-08-cncf-landscape/index.mdx
- website/docusaurus.config.ts
- website/src/components/CustomGitHubButton.tsx
- website/src/pages/index.module.css
- website/src/pages/index.tsx
- website/src/theme/NavbarItem/ComponentTypes.ts
- website/src/theme/NavbarItem/NavbarWrapper/index.tsx
- website/src/theme/NavbarItem/NavbarWrapper/styles.module.css
Closes #459
- Adding the GitHub star button (also on mobile)
- Adding the Producthunt Button on the website and README.md
- Adding an announcement bar
> docs(website): add star counter, add producthunt banner

- cmd/glasskube/cmd/version.go
Closes https://github.com/glasskube/glasskube/issues/529
Changed the error message to show that the glasskube is not bootstrapped yet do it using glasskube bootstrap command.
> glasskube version show an error when not bootstrapped

- cmd/glasskube/cmd/describe.go
- go.mod
- go.sum
- internal/cliutils/markdown.go
- internal/web/templates.go
- internal/web/templates/pages/package.html
Closes #253  
This PR adds support for rendering the package LongDescription as markdown in the CLI (describe command) and UI (details page).
Markdown parsing is achieved using https://github.com/yuin/goldmark. For the CLI we use a custom renderer.
> feat(cli, ui): add markdown support in long description

- website/docs/04_design/package-config.md
> docs(website): remove version disclaimer

- internal/manifestvalues/patch.go
Currently, the patches generated from a packages value definitions and configurations are non-deterministic because the operator ranges over the value definitions map directly. This PR changes this behavior by ranging over the sorted list of map keys instead, thus making it deterministic.
This is not a problem for any current packages because it only manifests if two value definitions contain targets with the same path.
> fix(package-operator): make order of patch application deterministic

- cmd/glasskube/cmd/bootstrap.go
- internal/util/pointer.go
Checking the operator version does not make sense for the `bootstrap` command, because the version is about to be upgraded anyways. This PR removes this check for the `bootstrap` command.
> fix(cli): skip version check for `bootstrap`

- cmd/glasskube/cmd/bootstrap.go
- pkg/bootstrap/bootstrap.go
Closes #454 
This PR adds a validation step to the bootstrap command: If any resource has the "kubectl last applied configuration" annotation, the operation is cancelled and no changes are made. This can be overridden using the new `--force` flag.
> fix: add validating existing install before bootstrap

- cmd/glasskube/cmd/install.go
- cmd/glasskube/cmd/update.go
Closes #463
The PR make changes to `-v/--version` in the glasskube cli. Previously it requires the user to add "v" prefix to the version. With the PR the user will be able to pass exact version and the code internally adds a "v" prefix.
> fix(cli): version prefix v now is now optional

- website/guides/04_kubectl-guide.mdx
Added a section that was missing to the useful flags to include the --dry-run=[client/server] flag plus a use case on how to use it with sealed secrets.
> docs(website): update --dry-run flag section

- cmd/glasskube/cmd/list.go
- go.mod
- pkg/list/list.go
Closes #465 
Fixes #465
This PR adds the feature of printing the list subcommand in the `json` format.
In this code I tried the `JSON.Marshal()` function but the output was not quite readable, hence went with the approach of 
`JSON.MarshalIndent()`.
> feat(cli): add json and yaml format in the list sub-command

- internal/web/components/pkg_detail_btns/controller.go
- internal/web/components/pkg_overview_btn/controller.go
- internal/web/templates/components/pkg-detail-btns.html
- internal/web/templates/components/pkg-overview-btn.html
…installed (#456)
Closes #456 
Shows Uninstalling package button when the package is being uninstalled
On package overview page
On package details page
> feat(ui): show uninstalling button if a package is currently being uninstalled (#456)

- internal/clientutils/autoupdate.go
- internal/telemetry/properties/builder.go
- pkg/client/builder.go
Closes #634 
This pull request refactors the codebase to utilize annotations for managing package auto-update information. This aligns with recommended practices in Kubernetes, as annotations are the preferred method for storing non-identifying, descriptive information.
Previously, the `packages.glasskube.dev/auto-update` label served the purpose of indicating whether a package should be automatically updated. However, labels are more suited for identifying resources, while annotations provide a better fit for non-critical data like auto-update settings.
This change ensures consistency and adherence to Kubernetes best practices, without altering the intended functionality for automatic package updates.
> refactor: auto-update label to annotation

- pkg/client/package_status.go
Closes #654
Shows uninstalling state when a package is being uninstalled using the `list` and `describe` command.
> feat(cli): shows uninstalling status when a package is being uninstalled using the list and describe command (#654)

- cmd/glasskube/cmd/root.go
- internal/cliutils/inputs.go
- internal/config/config.go
This PR adds a new persistent flag to the root command: `--non-interactive`. If this flag is used and the application would reach a state where it would normally wait for user input, it will instead show an error message and terminate with an error code.
> feat(cli): add flag to trigger non-interactive mode

- cmd/package-operator/main.go
This PR fixes a but that causes the operator to crash repeatedly when trying to install a package with dependencies
> fix(package-operator): add missing repoclient

- cmd/glasskube/cmd/install.go
- cmd/glasskube/cmd/root.go
- cmd/glasskube/cmd/uninstall.go
- cmd/glasskube/cmd/update.go
Closes #709 
This PR adds support for `--no-progress` flag applicable globally to glasskube cli for the prevention of status/progress logging during the execution of a command. Currently affected commands are:
1. `install`
2. `uninstall`
3. `update`
> feat: add --no-progress cli flag (glasskube#709)

- cmd/glasskube/cmd/serve.go
- go.mod
- internal/web/server.go
Additional logging via klog (https://github.com/kubernetes/community/blob/master/contributors/devel/sig-instrumentation/logging.md) can be activated with the `--log-level` flag – for now mostly for debugging out-of-sync issues on the UI server. It is not supported yet for any other command than `serve`.
> feat(ui): introduce additional logging

- cmd/glasskube/cmd/uninstall.go
Closes #760
This PR changes flag name of --force to --yes for glasskube uninstall
This is a breaking change for the CLI as the --force flag is replaced with --yes for consistency. Here's a screenshot of the flags available for glasskube uninstall :
And here's the flag in action:
As this is my first PR I hope I've followed the contributing guide (really nice guide) and don't hesitate to point me to any changes and improvements so I can create better PR for this cool project
> feat(cli): change flag from --force to --yes for glasskube uninstall

- cmd/glasskube/cmd/serve.go
- internal/web/server.go
Closes #753  
Introduce `--skip-open` support for `glasskube serve` to skip opening the browser.
> feat(cli): introduce `--skip-open` support for `glasskube serve`

- internal/httperror/error.go
- internal/web/discussions.go
Closes #755 
This PR suppress the `failed to get discussion counts from giscus: wrong status code: 404 Not Found` message from the command line if we get a 404 calling gitcus API. Also this PR fixes an issue with the Is function found in the httperror package
My intention was to use the httperror.IsNotFound function to suppress the message, but I was having a problem with that function as it always returned false if I tested to get a package with no discussion. I debugged the httperrors.IsNotFound function and it seems that httperrors.Is had an issue. I've changed `var statusErr statusError`
```
func Is(err error, code int) bool {
var statusErr *statusError  <----
if errors.As(err, &statusErr) {
return statusErr.code == code
}
return false
}
```
I think that statusError must be a pointer …
> fix(ui): suppress 404 error for packages w/o a giscus discussion

- cmd/glasskube/cmd/bootstrap.go
- internal/cliutils/setupclientcontext.go
- internal/web/server.go
- pkg/bootstrap/bootstrap.go
Closes #724 
Fixes #724 
This PR adds the feature for receiving JSON/YAML output for bootstrap command. This gives an output of all the Kubernetes Resources that are changed. 
1. Give a bootstrap command with the flags `-o` add YAML or JSON to it
2. Now it will first bootstrap the cluster as it will normally do (unless an error occurs)
3. After the bootstrap is completed successfully it will show all the changed Resources in the format you gave in.
something like this:
```
≡ƒºè The next generation Package Manager for Kubernetes ≡ƒôª
* Fetching Glasskube manifest from https://github.com/glasskube/glasskube/releases/download/v0.8.0/manifest-aio.yaml
* Validating existing installation
* Applying Glasskube manifests
* Telemetry is enabled for this cluster ΓÇô Run "glasskube telemetry status" …
```
> feat(cli): add `--output` flag for `glasskube bootstrap`

- cmd/glasskube/cmd/repo_add.go
- cmd/glasskube/cmd/repo_update.go
- internal/cliutils/packagerepository.go
- website/docs/04_design/repositories.md
Closes #806 
This PR changes `repo add --default` so we can only have one default repository
If we now add a new repo using the --default flag we can have two or more repositories with the default annotation set. With this PR the command updates the current default repo to remove the default annotation so we only have one default repository. If we've an error when adding the new repo we roll back and set the default annotation for the previous repo.
> fix(cli): `repo add --default` removes annotation for current default repo

- go.mod
- internal/web/templates.go
Closes #832 
This PR makes links in package description open in a new tab: `target="_blank" rel="noopener noreferrer"`
This PR uses https://pkg.go.dev/golang.org/x/net/html to parse the html and manipulate the nodes to add the target and rel attributes to any link found in the converted markdown. Here's a vide showing the new behavior:
https://github.com/glasskube/glasskube/assets/30386061/fbb2c376-ceaf-45f4-a9f7-b96aaac58c2e
> fix(ui): open package description links in new tab

- internal/manifest/helm/flux/adapter.go
- internal/names/names.go
- pkg/open/open.go
Closes #844 
Try different service names when opening a package that includes a helm release:
1. entrypoint name
2. package name + entrypoint name (joined with "-")
3. package name + chart name + entrypoint name (joined with "-")
4. package name + chart name (joined with "-")
> fix(open): try different service names

- internal/web/server.go
- pkg/client/client_cached.go
- pkg/client/cluster_package.go
- pkg/client/interface.go
- pkg/client/package.go
- pkg/client/packageinfo.go
- pkg/client/packagerepository.go
- pkg/install/install.go
- pkg/uninstall/uninstall.go
- pkg/update/update.go
Ref #838 
This is an attempt at making the out of sync problem less likely to happen, by passing a fixed timeout in the API call (like also all standard listers for namespace, secrets, etc do). The "base" timeout is set by the lister/watcher of the go client, but we divide it by 10 to "force" rewatches in smaller iterations. This should lead to re-watches every 30 - 60 seconds, so even if the out of sync issue appears, it would hopefully repair itself after at latest 1 minute. 
Additionally, by passing the given list options to our client, and reusing it rather than overwriting it, we will set the `allowWatchBookmarks` flag to true. Therefore we will also process `BOOKMARK` events, which might have an influence on the issue: https://stackoverflow.com/questions/66080942/what-k8s-bookmark-so …
> fix(client): propagate list options and apply timeout

- website/docs/03_components/02_package-operator.md
- website/guides/01_cert-manager.mdx
- website/guides/02_ingress-nginx.mdx
Closes #881 
Fixed Broken link in website docs which caused error while building
> docs(website): fix broken link

- cmd/glasskube/cmd/configure.go
- cmd/glasskube/cmd/describe.go
- cmd/glasskube/cmd/install.go
- cmd/glasskube/cmd/kind_options.go
- cmd/glasskube/cmd/open.go
- cmd/glasskube/cmd/output_options.go
- cmd/glasskube/cmd/repo_add.go
- cmd/glasskube/cmd/repo_options.go
- cmd/glasskube/cmd/repo_update.go
- cmd/glasskube/cmd/telemetry.go
- cmd/glasskube/cmd/uninstall.go
- cmd/glasskube/cmd/update.go
- internal/manifestvalues/flags/flags.go
We don't follow any rules when it comes to usage texts for the Glasskube CLI. This PR updates all usage texts and flag descriptions to follow the syntax described in http://docopt.org/
> fix(cli): standardize usage texts

- internal/web/templates/layout/base.html
Closes #866 
- Used the bootstrap class [`d-flex flex-row`](https://getbootstrap.com/docs/4.0/utilities/flex/) to bring down all the elements properly in a row. Since `ul` element by default had `flex-column` due to which they were stacking over each other.
https://github.com/glasskube/glasskube/assets/76129377/f02ece71-4a06-416a-b188-5edc495d796e
> fix(ui): improve navbar for smaller screens

- cmd/glasskube/cmd/describe.go
- cmd/glasskube/cmd/kind_options.go
- pkg/describe/describe.go
Ref #803 
The new behavior of `glasskube describe` is as follows:
- if there exists a Package or ClusterPackage with name `pkgName`, that is described (also considering all flags like `--kind` and `--namespace`
- otherwise, if there exists a package in a repository with that name, that is described
- if that package has scope "Namespaced", additionally, a summary of all instances is shown
> feat(cli): add support for describing namespaced packages

- cmd/glasskube/cmd/auto-update.go
The command does actually require a bootstrapped cluster, but the check would require additional access rules and is not really necessary since the command would fail anyways if no package or clusterpackage crd is present in the cluster.
> fix(cli): remove bootstrap requirement from `auto-update` command

- internal/web/templates/layout/base.html
Closes #863 
Make the navbar header stick on top even if scrolling down.
*Old Behavior* - Even I scroll to bottom, navbar didn't stick on top.
*New Behavior* - Navbar stick on top even I scrolled down.
> fix(ui): sticky navbar

- internal/web/templates/components/pkg-config-input.html
Closes https://github.com/glasskube/glasskube/issues/850
Closes https://github.com/glasskube/glasskube/issues/849
Added asterisks to mandatory inputs if constraint is defined for that particular input.
> feat(ui): added asterisk for mandatory form inputs

- cmd/glasskube/cmd/repo_delete.go
Closes #681 
PackageRepositories now can be deleted using `repo delete [repoName]`
```
$ glasskube repo delete default                                                                                          
Repository default will now be deleted. Do you want to continue? y
Repository default has been deleted.
```
```
$ glasskube repo delete glasskube                                                                                        
Repository default will now be deleted. Do you want to continue? n
❌ Repository Deletion Cancelled
exit status 1
```
When a package is installed from the PackageRepository,
```
$ glasskube install cyclops                                                                                        
Version not specified. The latest version v0.7.1+1 of cyclops …
```
> feat(cli): support repo deletion with `repo delete [repoName]`

- internal/telemetry/client.go
- internal/web/cacheverifier.go
- internal/web/constants.go
- internal/web/server.go
Ref #838
Closes #768 
Undoes changes of #843
As the reconnection logic of #875 does not work yet, we want to provide users with a log message in the server, and shut it down so that it's necessary to restart manually again. This is of course far from ideal, but the best/cheapest way to tell the user something is wrong (the UI will show the "disconnected" banner when the server is down).
> fix(ui): show an error if the client cache is out of sync

- internal/web/templates/pages/package.html
…esent
Closes #788
When the user selects a version, a request to reload the package detail page is triggered. With the `hx-include` attribute, additional query parameters can be added to this request, such that in a multi-repo environment, the selected repository is sent additionally to the selected version. The referred to element (`#pkg-install-repository`) however, doesn't exist when there is only one repository, and therefore there was an error logged to the browser console. This should be gone now.
> fix(ui): avoid including repo parameter when only one present

- cmd/glasskube/cmd/list.go
- cmd/glasskube/cmd/update.go
Closes #899 
Fixes #899 
This PR adds the feature to display the package installation error message in the `glasskube ist` command
It looks something like this:
```powershell
NAME                   STATUS         VERSION                                          AUTO-UPDATE  MESSAGE …
```
> feat(cli): display status message in `glasskube list`

- internal/web/discussions.go
This was not found til now, because we only show the discussion link for packages of the glasskube repo, which only since a short time includes a namespaced scoped package. The link in the `pkg-detail-header` to the discussion page was broken for uninstalled namespaced packages (it linked to `/packages/quickwit///discussion`), which lead to an `404` error, rerouting the client to the package overview page (this is a mechanism introduced to redirect from a namespaced package detail page to the overview page, after the package has been deleted). 
The fix makes the link go to `/packages/quickwit/-/-/discussion`.
> fix(ui): discussion page for uninstalled namespaced packages

- internal/clientutils/resources.go
Closes #952
Added condition to ignore appending yaml parsed object to the `resources` array if its empty
I tested my code by setting up a local package repository and adding `gateway-api` as an example to it. Now installation finishes successfully
> fix(client): ignore empty yaml objects

- package-lock.json
- package.json
- web/index.js
- web/windowHtmx.js
Relevant links:
* https://htmx.org/posts/2024-06-17-htmx-2-0-0-is-released/
* https://htmx.org/migration-guide-htmx-1/
Seems to me that everything is still working as before:
* swapping page contents
* receiving SSE events and triggering refreshes
* swapping errors to the correct container (`response-targets` extension)
> chore(ui): update htmx to v2

- pkg/bootstrap/bootstrap.go
Ref #948 
1. The progressbar would report an incorrect message most of the time because of the default throttle config
2. The error message in case a workload does not become ready was not helpful
> fix(cli): improve bootstrap progressbar accuracy and error message

- website/docs/05_comparisons/01_helm.md
I added the Helm or no Helm podcast to the Helm comparison page.
@jakepage91 as I am not an expert in Twitter spaces. Do you think it makes sense to add Audio Bookmarks to the covered topics so listeners can jump to the correct sections right away?
> docs(website): add Helm or no Helm podcast

- cmd/glasskube/cmd/configure.go
Closes #867 
`glasskube configure <package-without-configuration-values>`  will throw message as 'This package has no configuration values'
and exit.
> feat(cli): add `glasskube configure` showing an error for package with no value definitions

- cmd/glasskube/cmd/list.go
Ref #928 
Have added support for for -o , --output flag for kind package. Earlier this was only functional for kind clusterpackage.
> fix(cli): `list` command with `--output` flag respects `--kind` flag

- cmd/glasskube/cmd/bootstrap.go
- pkg/bootstrap/bootstrap.go
Closes #900 
When --no-progress flag is passed with bootstrap cmd then status message's and progress bar will not be shown on cli.
> fix(cli): add handling of `--no-progress` flag for `glasskube bootstrap`

- cmd/glasskube/cmd/serve.go
Accidentally changed in https://github.com/glasskube/glasskube/pull/1027
> chore(cli): revert accidental change of default `serve` port

- internal/webhook/package_validator.go
Closes #953 
Added scope validation for creation of Package/ClusterPackage resouces.
The only supported combinations of resource type - manifest scope:
- ClusterPackage - Cluster
- Package - Namespaced
Anything else should not lead to the creation of the resource.
A check that compares the Manifest and Package's scope is added
> fix(package-operator): add validation of scope during package creation/update

- internal/repo/client/clientset.go
Closes #988 
This PR adds checking of the repo spec when requesting a repo client from the clientset.
When requesting via name, it checks if the repo spec has been checked in the last 30 seconds (default) and checks again if it is older than that.
> fix: add repoclient invalidation

- website/src/data/packages.ts
Updated packages page on website to include Kwasm and SpinKube to the `planned` section and also updated the NFD icon as well as removing the `planned` tag.
> docs(website): updated packages page

- cmd/glasskube/cmd/list.go
- pkg/list/lister.go
Closes #865
Adds the optional argument `<packageName>` and optional flag `--namespace`to the `list` cmd.
```
glasskube list quickwit
```
```
glasskube list quickwit --namespace foo
```
```
glasskube list --kind clusterpackage --namespace default
```
```
glasskube list quickwit --kind clusterpackage
```
* The empty list error handling has been replaced with just one single message `No <resource> found.` for every case. Due to the different options to combine flags, sometimes multiple error messages are valid. It is hard to decide which one takes precedence. A simple single error message is less confusing instead.
* Introducing tests for list command. There is some complexity on how the flags interact with each other. Introducing new flags needs changes on retrieval logic and output logic. …
> feat(cli): add support for filtering package list by name and namespace

- internal/manifest/helm/flux/adapter.go
Related to #60 
This PR reduces the number false positive errors during package installation. These false positives were caused by the operator encountering conflicts during the reconciliation of dependent HelmRelease and HelmRepository resources. 
This PR does not resolve #60, but it makes the issue less urgent, since it eliminates a big class of real-world errors that it would deal with.
> fix(package-operator): add retry-on-conflict for reconciling helm resources

- internal/web/server.go
- internal/web/templates/components/version-mismatch-warning.html
Closes #1071 
Changed the warning message when operator version is less than client version in UI when GitOps mode is enabled.
> chore(ui): improve update instructions in GitOps mode

- api/v1alpha1/package_manifest.go
- internal/manifest/helm/flux/adapter.go
Closes #1087 
When pulling from an OCI repo, flux needs the type of the helm repository to be set to "oci". We use the URL scheme as a heuristic to determine the repo type on the fly: if the url starts with "oci://" we assume the type "oci", otherwise "default".
Reference https://fluxcd.io/flux/components/source/helmrepositories/#helm-oci-repository
> fix(package-operator): always set the correct type for HelmRepositories

- api/v1alpha1/package_manifest.go
- api/v1alpha1/packageinfo_types.go
- config/crd/bases/packages.glasskube.dev_packageinfos.yaml
- internal/controller/common.go
- internal/controller/packageinfo_controller.go
- internal/manifest/adapter.go
- internal/manifest/helm/flux/adapter.go
- internal/manifest/plain/adapter.go
- internal/manifest/plain/adapter_test.go
- internal/manifest/plain/suite_test.go
Closes #1085  
This PR adds handling of local path manifest URLs in package manifests. In order to ensure that the operator always uses the correct base URL, the resolved URL of the package.yaml is stored in the PackageInfo status and all local paths are resolved relative to that.
> feat(package-operator): add handling of local path manifest url

- PROJECT
- cmd/cert-manager/main.go
- cmd/package-operator/main.go
- config/crd/kustomization.yaml
- config/crd/patches/cainjection_in_packagerepositories.yaml
- config/crd/patches/webhook_in_packagerepositories.yaml
- config/webhook-local/webhook_manifests_patch.yaml
- config/webhook/manifests.yaml
- internal/webhook/errors.go
- internal/webhook/packagerepository_webhook.go
- internal/webhook/packagerepository_webhook_test.go
Closes #871 
Adds a validating webhook for the package repository resource
* Upon deletion of a repository, or update of the URL of a repository, the following validation is performed:
* If no packages are installed, the delete/update proceeds as normal. If packages are installed, an error with the list of installed packages is shown
* ```
k delete packagerepositories.packages.glasskube.dev test
Error from server (Forbidden): admission webhook "vpackagerepository.kb.io" denied the request: dependent package(s) installed: [{ingress-nginx v1.9.5+1 test}]
```
> feat(package-operator): add package repository validating webhook

- package.json
The npm spec requires name (and version) fields. I did this because I ran into build difficulties due to its omission.
Closes # 
Just added a 'name' property, [as demanded by the npm spec](https://docs.npmjs.com/creating-a-package-json-file#required-name-and-version-fields).
> chore: add name field to package.json

- website/src/partials/_install.mdx
In the [Installation Guide](https://glasskube.dev/docs/getting-started/install/), the instructions for Alpine Linux contain 2 mistakes:
- the filename of the package is incorrect
- the package is untrusted by Alpine, therefore the `--allow-untrusted` option is missing
Thus, simply copy/pasting the commands will result in an error (even though it is easy to overcome).
N/A
> docs(website): correct install command for Alpine Linux

- internal/webhook/packagerepository_webhook.go
- internal/webhook/packagerepository_webhook_test.go
Closes #1155
This should at least fix one part of the #1155 issue. Problem was that it was not allowed to update a package repository if the URL did not change, due to a missing else branch.
I don't know about the first part of the issue though (certificate error – pretty sure that only happens during the update of an installation, and maybe the cert-manager generates a new cert there and it's just not ready in time?).
> fix(package-operator): package repository webhook validation

- internal/manifestvalues/cli/configure.go
Closes #1022
Adds Markdown rendering support to the glasskube configure command, aligning it with the existing functionality in the describe command.
- Created `PrintMarkdown` utility in `internal/manifestvalues/cli/configure.go`
> feat(cli): add markdown support for value descriptions when configuring a package via CLI

- website/blog/2023-12-14-5-helm-shortcomings/index.mdx
- website/blog/2024-02-01-technical-preview/index.mdx
- website/blog/2024-02-08-cncf-landscape/index.mdx
- website/blog/2024-02-12-open-command/index.mdx
- website/blog/2024-02-14-kubernetes-frontends/index.mdx
- website/blog/2024-02-27-release-package-updates/index.mdx
- website/blog/2024-03-22-release-0.1.0/index.mdx
- website/blog/2024-03-26-discord-setup/index.mdx
- website/blog/2024-04-04-contributor-guidelines/index.mdx
- website/blog/2024-04-26-beta-launch-blog/index.mdx
- website/blog/2024-05-20-devops/index.mdx
- website/blog/2024-07-02-quickwit/index.mdx
- website/blog/2024-08-06-IDP/index.mdx
Added the blog. 
I found this issue that added support for canonical links [here](https://github.com/facebook/docusaurus/issues/2603), even though I didn't find clear instructions in the official docs.
> docs(website): added Series A IDP blog post to blog section

- Makefile
Closes #813  
This PR updates the `cert` Makefile target to use the system's default temp file directory. Previously we assumed that it is always at /tmp but that is apparently not the case. 
- https://apple.stackexchange.com/questions/353832/why-is-mac-osx-temp-directory-in-weird-path
- https://unix.stackexchange.com/questions/174817/finding-the-correct-tmp-dir-on-multiple-platforms
> build: use system tmpdir for webhook cert

- .goreleaser.yaml
Completions introduced in https://github.com/glasskube/glasskube/pull/1192 fail due to the projects like https://github.com/go-task/task have a completions folder which they just copy into the local home directory.
> fix(build): fix completions

- .goreleaser.yaml
Resolves issue with Completions introduced in https://github.com/glasskube/glasskube/pull/1192
Removes three install lines from previous commit and uses homebrew function in post_install block to generate and install the completions
[Class: Formula      — Homebrew Ruby API](https://rubydoc.brew.sh/Formula.html#generate_completions_from_executable-instance_method)
> feat: generate completions after brew install

- internal/web/templates/layout/base.html
The Giscus backlink is put into the github discussion content. 
A link to 127.0.0.1 doesn't make a lot of sense to anyone who doesn't have glasskube installed or not running right now, or running on a different host / port. So I changed the backlink to our public packages page on the website (discussable if useful, but leaving it empty does not seem to be an option). 
Giscus Docs https://github.com/giscus/giscus/blob/main/ADVANCED-USAGE.md#giscusbacklink
> fix(ui): use hardcoded giscus backlink

- internal/dependency/graph/graph.go
- internal/dependency/graph/graph_test.go
When two version numbers of a package only differ in the metadata, we did not deterministically calculate which version to choose. We now also try to interpret the metadata. We still do not consider the metadata in constraints though, as by design.
> fix: consider metadata when calculating max version

- website/guides/08_package-creation.mdx
Guide "How to add a Package to Glasskube" contained a link to the design document "Package Configuration". The link was `04_design/package-config.md` but since then, the folder has been renamed `05_design/package-config.md`.
> docs(website): fix link to package configuration design documentation in guides

- website/docs/05_design/dependency-management.md
Diagrams are often easier to read and grasp than text. The dependency management algorithm is such an example.
I translated the textual description to a Mermaid diagram with an intuitive color coding:
- Green means no change
- Yellow means successful change
- Red means failure
Here is a screenshot of what it looks like:
> docs: use a mermaid diagram for the dependency management algorithm

- web/custom.js
When opening a modal, the previous content is still there until it is swapped out. Sometimes on slow requests, that can be confusing. When the new modal request errors, there might be a toast shown but also the previous content is still there. This would be a hack to avoid that confusion. 
Use cases where this might occur: installing a namespaced package in gitops mode, using a namespace that does not exist yet. The dry-run installation will throw an error because of that, but the modal will still be shown with the previous content.
> fix(ui): clear previous modal content

- internal/manifest/plain/prefix.go
Some packages contain CRDs where another operator manages some dependent resources. In some cases it can be necessary to refer to those resources by use of a label selector. If supported by a CRD, it would make sense to add the package operator labels to those resources, but for that the package operator needs to know about those fields. 
This PR introduces a list of "well-known" label field specs. Those are field specs of label maps in some widely used CRDs. Currently there is only one well-known label field spec, namely in the Keycloak CRD provided by the keycloak-operator-crds package.
> feat(package-operator): add "well-known" label field specs

- internal/web/packagedetail.go
`.GitopsMode` template variable was missing when `component=header` was requested, and therefore the `ForPkgDetailHeader` function could not parse it to a bool
> fix(ui): package detail header breaks when rendering

- website/blog/2024-10-11-helm-guide/index.mdx
Found a couple of typos that needed fixing in the helm guide.
> docs(website): fix typo's in helm guide
