glasskube/glasskube

- README.md
Currently, the readme fails to mention the `glasskube bootstrap` step. This PR fixes that and adds some more text for fluff. :sheep:
> docs: update quick start section in readme

- website/docs/02_getting-started/01_install.md
- website/docs/02_getting-started/01_install.mdx
- website/docs/02_getting-started/02_bootstrap.mdx
- website/docs/04_guides/01_cert-manager.mdx
- website/src/partials/_install.mdx
This PR adds some content in the "Getting started" section of our docs. 
I moved the tabbed installation info into a separate file that can be reused in several places.
> docs: getting started section

- website/docs/02_getting-started/01_install.mdx
- website/docs/04_guides/01_ingress-nginx.mdx
- website/docs/04_guides/02_ingress-nginx.mdx
- website/src/partials/_install.mdx
This PR adds a guide about installing ingress-nginx using glasskube
> docs: add ingress-nginx guide

- website/docs/03_components/01_client.md
- website/docs/03_components/02_package-operator.md
- website/docs/03_components/02_package-repository.md
- website/docs/index.md
Updating docs: Welcome page cleanup, components.
> docs: update component descriptions

- website/docs/05_comparisons/_category_.yaml
- website/docs/05_comparisons/helm.md
This PR adds a new category and page in the docs, where we compare glasskube and helm
> docs: add helm comparison

- README.md
SVG looks much nicer than GIF
Preview: https://github.com/glasskube/glasskube/blob/kosmoz/readme-svg/README.md
I used this tool: https://github.com/marionebl/svg-term-cli
> docs: replace gif in readme with svg

- website/blog/2023-01-11-welcome/index.md
- website/blog/2023-02-01-technical-preview/index.mdx
Add a first blog post about our first technical preview release
- Sections about Glasskube und Helm still need to be improved.
- Screenshots need to be added.
> docs: add technical preview blogpost

- website/docs/04_comparisons/helm.md
> docs: update helm comparison

- website/docs/02_getting-started/01_install.mdx
This PR adds documentation for a very useful feature of the CLI :-)
> docs: add shell completion to install guide

- website/src/pages/roadmap.md
The roadmap was out of date. This PR updates it.
> docs: update roadmap

- cmd/glasskube/cmd/install.go
- internal/web/server.go
- pkg/install/install.go
- pkg/statuswriter/noop.go
- pkg/statuswriter/spinner.go
- pkg/statuswriter/statuswriter.go
- pkg/statuswriter/writer.go
Ref #168
This PR adds a nice progress spinner when running `glasskube install [package]`.
> feat(cli): add progress spinner for install cmd

- config/manager/kustomization.yaml
- release-please-config.json
Currently the manifest installs the `latest` tag. This PR changes the manifest so it installs the current version.
The version should be updated by release please.
> fix(package-operator): add version in manifest

- .golangci.yml
- CONTRIBUTING.md
- Makefile
- cmd/glasskube/cmd/bootstrap.go
- cmd/glasskube/cmd/install.go
- cmd/glasskube/cmd/list.go
- cmd/glasskube/cmd/root.go
- cmd/glasskube/cmd/serve.go
- internal/bootstrap/validate.go
- internal/clientutils/resources.go
- internal/cliutils/table.go
- internal/cmd/schema-gen/main.go
- internal/constants/constants.go
- internal/repo/repo.go
- internal/web/server.go
- pkg/bootstrap/bootstrap.go
- pkg/client/client.go
- pkg/client/package.go
- pkg/client/package_status.go
- pkg/list/list.go
- pkg/statuswriter/spinner.go
- pkg/statuswriter/writer.go
- pkg/uninstall/uninstall.go
This PR enables the Golang Linter during the build and fixes all linter errors we had so far.
> ci: enable linter

- website/src/data/packages.tsx
- website/src/pages/roadmap.md
Closes #137
Support keptn pages
> feat: support keptn package installation via Glasskube

- cmd/glasskube/cmd/open.go
- go.mod
- go.sum
- internal/cliutils/browser.go
- internal/web/server.go
- pkg/client/client.go
- pkg/client/context.go
- pkg/client/package.go
- pkg/client/package_status.go
- pkg/client/packageinfo.go
- pkg/future/future.go
- pkg/kubeconfig/new.go
- pkg/open/open.go
- pkg/open/prefixwriter.go
- pkg/open/result.go
- website/docs/index.md
Closes #107
Closes #108
This PR adds the `glasskube open` subcommand.
> feat: add `glasskube open` cmd

- README.md
- website/blog/2024-02-08-cncf-landscape/index.mdx
add glasskube is part of the cncf landscape blog post
> docs(website): add glasskube is part of the cncf landscape blog post

- cmd/glasskube/cmd/install.go
- cmd/glasskube/cmd/list.go
- cmd/glasskube/cmd/serve.go
- internal/repo/repo.go
- internal/web/components/installbutton.go
- internal/web/server.go
- internal/web/templates/components/installbutton.html
- pkg/client/packageinfo.go
- pkg/list/list.go
- pkg/open/open.go
- pkg/open/result.go
Closes #109 
This PR changes the "installed" button into an "open" button if a package has at least one entrypoint.
> feat(ui): add open button on list page

- website/docusaurus.config.ts
fix the typo from "Book appoitment" to "Book appointment"
> Bug: fix the typo 

- api/v1alpha1/package_manifest.go
- internal/web/templates/pages/packages.html
- schema/package-manifest/schema.json
Closes #206  
Supporting svg elements in iconUrl
Changed the properties of img in packages.html to support svg without changing dimensions. Added a commit to package manifest, iconUrl to particularly accept an url format.
> fix(package manifest): changed the schema and supported svg format elements

- cmd/glasskube/main.go
- internal/cliutils/checkforupdate.go
Closes #210
Added an internal cliutil - checkforupdate.go which checks for updates and notifies the user
Whenever the glasskube is run in the CLI it always checks for the update before executing other subcommands such as list or serve.
> feat: added a feature to detect outdated client for cli (#210)

- README.md
- website/blog/2024-02-01-technical-preview/index.mdx
- website/blog/2024-02-08-cncf-landscape/index.mdx
- website/blog/2024-02-12-open-command/index.mdx
- website/src/pages/roadmap.md
> docs(website): add v0.0.2 release blogpost

- website/blog/2024-02-14-kubernetes-frontends/index.mdx
- website/blog/authors.yml
Add a blogpost about kubernetes frontends.
> feat(website): add blogpost about kubernetes frontends

- internal/web/root/static/css/base.css
- internal/web/templates/components/pkg-detail-btns.html
- internal/web/templates/components/pkg-overview-btn.html
- internal/web/templates/layout/base.html
- internal/web/templates/pages/package.html
- internal/web/templates/pages/packages.html
This PR introduces proper handling of page updates when the user navigates between pages via browser history (back, forth). The content of the package overview and package detail page is being refetched when the `htmx:historyRestore` event is triggered. 
Additionally there is an infinite progress bar for any kind of AJAX call via htmx.
> fix(ui): support browser history and progress bar

- cmd/glasskube/cmd/bootstrap.go
- cmd/glasskube/cmd/serve.go
- internal/cliutils/kubeconfig.go
- internal/cliutils/setupclientcontext.go
- internal/web/components/pkg_detail_btns/controller.go
- internal/web/components/pkg_overview_btn/controller.go
- internal/web/server.go
- internal/web/templates.go
- internal/web/templates/pages/bootstrap.html
- internal/web/templates/pages/support.html
- pkg/bootstrap/validate.go
- pkg/client/context.go
- pkg/kubeconfig/new.go
Closes #123
This PR introduces a better UI support page for when Glasskube is not bootstrapped in the cluster yet.
> feat(ui): bootstrap via UI #123

- internal/cliutils/setupclientcontext.go
- pkg/bootstrap/validate.go
Closes #196
This PR introduces a check at every bootstrap-required command, whether glasskube is bootstrapped + additionally asks the user if they want to bootstrap if not.
> feat(cli): automatic bootstrap #196

- cmd/glasskube/cmd/uninstall.go
Closes #270 
Add `CurrentContext` in uninstall cmd.
> feat: Add current context in uninstall

- Makefile
- config/crd/bases/packages.glasskube.dev_packageinfos.yaml
- config/crd/bases/packages.glasskube.dev_packages.yaml
Closes #266 
This PR should fix compatibility with Go v1.22.
Release notes: https://github.com/kubernetes-sigs/controller-tools/releases/tag/v0.14.0
> chore: update controller-tools to v0.14.0

- pkg/open/open.go
This PR fixes the `open` cmd, which is currently broken for versioned packages.
> fix: change opener to use real PackageInfo name

- cmd/glasskube/cmd/install.go
- internal/web/server.go
- internal/web/templates.go
- internal/web/templates/components/pkg-detail-btns.html
- internal/web/templates/components/pkg-install-modal-versions.html
- internal/web/templates/components/pkg-install-modal.html
- internal/web/templates/components/pkg-overview-btn.html
- internal/web/templates/layout/base.html
- pkg/list/list.go
Part of #269
This PR adds a modal dialog for package installation, where the user can choose between all available versions and to enable auto - updates or not. 
Update will be done in a separate PR.
> feat(ui): install package in specific version (#269)

- cmd/glasskube/cmd/update.go
- internal/httperror/error.go
- internal/repo/repo.go
- pkg/client/package.go
- pkg/statuswriter/spinner.go
- pkg/update/update.go
- website/docs/index.md
Closes #202 
The `update` command has two modes of operation:
* `glasskube update`: updates all installed packages 
* `glasskube update [packages...]`: updates selected packages
Before updates are applied, all changes are shown and the user is asked to confirm.
> feat(cli): add update cmd (#202)

- cmd/glasskube/cmd/serve.go
- cmd/glasskube/cmd/uninstall.go
- internal/web/configloader.go
- internal/web/error.go
- internal/web/handler/enricher.go
- internal/web/handler/precondition.go
- internal/web/server.go
- internal/web/templates.go
- internal/web/templates/pages/bootstrap.html
- internal/web/templates/pages/kubeconfig.html
- internal/web/templates/pages/support.html
- pkg/bootstrap/validate.go
- pkg/client/client.go
- pkg/client/context.go
- pkg/kubeconfig/new.go
- pkg/manifest/manifest.go
> feat(ui): add selecting kubeconfig (#140)

- cmd/glasskube/cmd/uninstall.go
- internal/web/server.go
- pkg/uninstall/uninstall.go
Closes one part of #168 
This pull request introduces several enhancements to the `uninstall` command:
**Uninstall Blocking**: Prevents the application from being uninstalled while processes are still running. This improves user experience by avoiding unexpected behavior.
**Progress Spinner**: Provides visual feedback to the user during the uninstallation process, indicating the progress and preventing confusion.
**Enhanced CLI UI**: Improves the cli ui for the uninstall command using visual effects
> feat: Introduced Uninstall Blocking, Progress Spinner and enhanced CLI UI

- internal/web/server.go
- internal/web/templates/components/pkg-update-modal.html
- internal/web/templates/pages/packages.html
Closes #289
Added an Update All button on the package overview page if there is at least one package not up to date.
> feat(ui): update all packages #289

- cmd/glasskube/cmd/describe.go
- internal/repo/repo.go
- internal/web/templates.go
- pkg/describe/describe.go
- website/docs/index.md
> feat(cli): glasskube describe (#241)

- internal/web/server.go
- internal/web/templates/pages/support.html
> fix(ui): support page error when no context given

- website/blog/2024-02-27-release-package-updates/index.mdx
- website/src/pages/roadmap.md
> docs(website): add v0.0.3 release blogpost

- pkg/bootstrap/validate.go
Closes https://github.com/glasskube/glasskube/issues/285
Fixes https://github.com/glasskube/glasskube/issues/285
This update runs the IsBootStrap function parallelly using Go Routines.
> feat(client): parallelize IsBootstrap function

- cmd/glasskube/cmd/install.go
Fixes #133 
Add CLI-Flag to not await install/uninstall commands
> feat(cli): add --no-await in install command

- pkg/describe/describe.go
Closes #303 
This PR adds falling back to fetching the manifest from the repo if either the PackageInfo doesn't exist (HTTP status code 404) or has an empty manifest in its status.
> fix(ui, cli): add fallback to manifest from repo

- .github/workflows/build.yaml
This should make the build faster, as the binaries are currently compiled for every run.
> ci: add caching of bin directory

- pkg/open/open.go
Closes #302
This PR changes the opener to choose the first ready pod matching the services label selector, rather than simply the first one. If no pod is ready, it fails.
> fix: change opener to choose first ready pod

- website/src/pages/roadmap.md
Our next release will be v0.1.0. This will allow us to easily add bugfix releases and increase release velocity.
> docs(website): adapt roadmap to match our new release convention

- cmd/glasskube/cmd/uninstall.go
Fixes #133 
Add CLI-Flag to not await install/uninstall commands
> feat(cli): add --no-await in uninstall command

- .golangci.yml
- go.mod
- go.sum
- internal/controller/package_controller.go
- internal/dependency/adapter/adapter.go
- internal/dependency/adapter/controllerruntime/controllerruntimeadapter.go
- internal/dependency/adapter/goclient/goclientadapter.go
- internal/dependency/dependency_suite_test.go
- internal/dependency/manager.go
- internal/dependency/manager_test.go
- website/docs/03_components/02_package-operator.md
Closes #311
This PR introduces checking versions of dependencies in the package controller. Therefore we use a newly added semver package.
> feat(package-controller): support versions for dependent packages (#311)

- internal/web/templates/components/pkg-update-modal.html
- internal/web/templates/pages/packages.html
Ref #355
This is just a temporary "fix" to avoid running into issues with the global update notification. In the long term bugs like #355 should be fixed by #357
> fix(ui): hide global update notification (#355)

- cmd/glasskube/cmd/bootstrap.go
- internal/cliutils/checkforupdate.go
Closes #240 
Added latest flag to bootstrap command to fix the development build error
> fix: bootstrap command development builds fix

- cmd/glasskube/cmd/describe.go
- cmd/glasskube/cmd/install.go
Ref #113 
This PR includes two changes:
1. The describe commands also shows dependencies (also the output of describe looks much nicer now :slightly_smiling_face:)
2. The install commands validates the dependencies of the installed package and shows all packages that would be installed. if there would be conflicts, it shows the conflicts and aborts.
> feat(cli): add dependencies in describe and install command

- release-please-config.json
The image kustomization was moved from manager to default, but the release-please config was never updated.
Noted in https://github.com/glasskube/glasskube/pull/366#issuecomment-1997244085
> chore: update release-please extra files

- website/src/pages/index.tsx
Add hs-script to newsletter on first form input change
> docs(website): add hs-script to newsletter

- Makefile
This PR adds the `GOCMD` variable to the Makefile. Using this variable it is now possible to specify a different Go binary.
This makes it much easier for developers to adopt newer Go versions, so we should be able to merge #278 sooner.
> build: add ability to override Go binary in Makefile

- api/v1alpha1/owned_resource.go
- cmd/glasskube/cmd/install.go
- config/crd/bases/packages.glasskube.dev_packages.yaml
- internal/controller/owners/owners.go
- internal/controller/owners/utils/owned_resources.go
- internal/controller/package_controller.go
- internal/dependency/adapter/adapter.go
- internal/dependency/adapter/controllerruntime/controllerruntimeadapter.go
- internal/dependency/adapter/goclient/goclientadapter.go
- internal/dependency/manager.go
- internal/dependency/manager_test.go
- internal/webhook/errors.go
- internal/webhook/package_validator.go
- internal/webhook/package_validator_test.go
> feat(package-operator): prevent invalid updates and deletions (#364)

- cmd/glasskube/cmd/bootstrap.go
- internal/cliutils/checkforupdate.go
- internal/cliutils/setupclientcontext.go
- internal/releaseinfo/releaseinfo.go
- internal/web/server.go
- internal/web/templates/pages/bootstrap.html
- pkg/bootstrap/bootstrap.go
This PR adds the "bootstrap latest" functionality to all other places where we bootstrap, aside from the `bootstrap` command.
This is a follow-up of #361.
> fix(cli, ui): add support for bootstrap latest via ui, implicit request

- cmd/glasskube/cmd/install.go
- internal/controller/package_controller.go
- internal/dependency/manager.go
- internal/dependency/manager_test.go
- internal/web/server.go
- internal/web/templates.go
- internal/web/templates/components/pkg-install-modal.html
- internal/web/templates/pages/package.html
- internal/webhook/package_validator.go
Ref #114
In this PR we add showing package dependencies on the package detail page, showing the list of installed packages (including dependencies) at the installation modal, and showing a list of dependency conflicts in case installation is not possible.
> feat(ui): handle dependencies (#114)

- internal/web/server.go
- internal/web/templates/components/pkg-overview-btn.html
- internal/web/templates/layout/base.html
> feat(ui): add notification on bad request

- internal/cliutils/checkforupdate.go
Closes #396
Thanks @Baalekshan for bringing this up!
> fix(cli): update check fails in dev environment

- cmd/glasskube/cmd/update.go
- internal/web/server.go
- pkg/update/update.go
> feat(cli, ui): show dependencies when updating

- internal/dependency/manager_test.go
> test: add tests for version range checking

- CONTRIBUTING.md
- website/docs/03_components/02_package-operator.md
- website/docs/03_components/03_package-repository.md
> docs: describe dependencies and changes to package repo (#316)

- internal/web/templates/layout/base.html
> feat(ui): alert when websocket has been closed (#222)

- website/blog/2024-03-22-release-0.1.0/index.mdx
- website/blog/authors.yml
Release post for v.0.1.0
This pic needs to be attached
> docs(website): add v0.1.0 release blogpost

- internal/semver/compare.go
- internal/semver/compare_test.go
This was more of an edge case previously, but now that updating to specific versions is becoming possible (#412), this should also be checked.
> fix: avoid updates to smaller versions

- CONTRIBUTING.md
> docs: update contributor guidelines

- website/src/pages/roadmap.md
We already released v0.1.0. This commit streamlines the public roadmap.
> docs(website): update roadmap

- website/blog/2024-03-22-release-0.1.0/index.mdx
- website/blog/2024-03-26-discord-setup/index.mdx
Publishing new blog post and also updating a screenshot in the previous v0.1.0 release blog
> docs(website): new Discord blog post + updated pic for v0.1.0 blog

- cmd/glasskube/cmd/describe.go
- cmd/glasskube/cmd/list.go
Closes #296 
This PR introduces the Auto-Update section in `list` and `describe` command which shows whether the package is marked for auto-updates.
```
$ ./glasskube ls
NAME                  STATUS         VERSION    AUTO-UPDATE
argo-cd               Not installed                      
cert-manager          Ready          v1.14.2+1  Enabled  
cyclops               Not installed                      
ingress-nginx         Not installed                      
keptn                 Ready          v0.10.0+1  Enabled  
kubernetes-dashboard  Not installed        
```
**If a package is installed** 
```
$ ./glasskube describe keptn
Package: keptn — Toolkit for cloud-native application lifecycle management
Version: v0.10.0+1
Status:  Ready
Auto-Update: Enabled
References: 
* Glasskube Package …
```
> feat(cli): show whether a package is auto-updated (#296)

- website/docs/03_components/03_package-repository.md
> docs: build numbers not allowed in dependency version ranges (#405)

- website/blog/authors.yml
streamlining avatar urls, updating louis linkedin link
> chore(website): update author avatar urls

- README.md
Adding https://repobeats.axiom.co/ analytics
Seen @ https://github.com/outline/outline
Will look like:
> docs: add glasskube activity chart

- cmd/glasskube/cmd/install.go
- internal/controller/package_controller.go
- internal/dependency/adapter/adapter.go
- internal/dependency/adapter/controllerruntime/controllerruntimeadapter.go
- internal/dependency/adapter/goclient/goclientadapter.go
- internal/dependency/default_repo_adapter.go
- internal/dependency/graph/errors.go
- internal/dependency/graph/graph.go
- internal/dependency/graph/graph_suite_test.go
- internal/dependency/graph/graph_test.go
- internal/dependency/manager.go
- internal/dependency/manager_test.go
- internal/dependency/types.go
- internal/names/package_info.go
- internal/names/utils.go
- internal/repo/client/fake/fakeclient.go
- internal/semver/compare.go
- internal/semver/errors.go
- internal/semver/validate.go
- internal/semver/validate_test.go
- internal/web/server.go
- internal/webhook/errors.go
- internal/webhook/package_validator.go
- internal/webhook/package_validator_test.go
- pkg/list/list.go
- pkg/manifest/manifest.go
- pkg/update/update.go
Closes #363
Changes the Dependency manager to use a dependency graph for validation. 
Should help with #344, #398, #399
> feat: add graph-based dependency validation

- internal/web/server.go
- internal/web/templates/components/pkg-update-modal.html
> feat(ui): reuse transaction when applying updates (#295)

- internal/web/server.go
- pkg/client/client.go
- pkg/client/package_cache.go
- pkg/client/packageinfo.go
- pkg/client/packageinfo_cache.go
> feat(client, ui): introduce package info cache (#444)

- cmd/glasskube/cmd/install.go
- cmd/glasskube/cmd/uninstall.go
- internal/controller/package_controller.go
- internal/dependency/manager.go
- internal/dependency/manager_test.go
- internal/web/server.go
- internal/web/templates.go
- internal/web/templates/components/pkg-detail-btns.html
- internal/web/templates/components/pkg-uninstall-modal.html
- internal/webhook/package_validator.go
- internal/webhook/package_validator_test.go
- pkg/uninstall/uninstall.go
- pkg/update/update.go
This PR partially implements #399 (only for package uninstallation).
> feat(cli, ui): show removed dependencies before uninstall

- internal/web/templates.go
- internal/web/templates/pages/package.html
Closes #330
Fixes #330
This shows the LatestVersion and the Current version (if installed) on the package overview page
Images :
- When a Package is installed 
- When a Package is not installed
> feat(ui): display latest version in package overview

- CONTRIBUTING.md
- website/blog/2024-03-26-discord-setup/index.mdx
- Adding video to contributor guidelines
- Fixing a couple incorrect links in the Discord blog post
Uploaded thumbnail
> chore(website): update link in blog + added video to cont guidelines

- website/blog/2024-04-04-contributor-guidelines/index.mdx
Added new blog post to the website called "Why contributor guidelines matter."
Images to be included
> docs(website): added new blog post - contributor guidelines

- cmd/glasskube/cmd/update.go
- pkg/update/update.go
Closes #412 
Fixes #412 
This code adds the `-v` flag in the update section. Using this user can update to any version of the package they desire.
I have tried replicating the `Prepare` function but for a single package.😊
> feat(cli): update to specific package version cli

- .github/CODEOWNERS
- renovate.json
Closes #380 (probably) 
Enables automerging dependencies for github actions and node modules.
> chore: add renovate automerge config

- website/src/pages/packages/index.tsx
- website/src/pages/packages/styles.module.css
Closes https://github.com/glasskube/glasskube/issues/481
I have changed the position of search bar in the center which will be more visible and user friendly. But i am open to suggestions on where else can i put it.
> Changed the position of searchbar in packages section of the website 

- cmd/glasskube/cmd/describe.go
- cmd/glasskube/cmd/list.go
- internal/clientutils/autoupdate.go
- internal/web/server.go
- internal/web/templates/pages/package.html
feat(ui): show whether a package is auto-updated (#296)
Closes #296
This PR adds an Auto-Update tag to the package details page.
> feat(ui): show whether a package is auto-updated (#296)

- cmd/glasskube/cmd/version.go
- internal/clientutils/versionutil.go
- internal/cliutils/versionutil.go
- internal/web/server.go
- internal/web/templates.go
- internal/web/templates/components/version-mismatch-warning.html
- internal/web/templates/layout/base.html
> feat(ui): show warning if operator and client versions differ (#352)

- website/docs/05_comparisons/02_timoni.md
The link to Timoni website was pointing to helm.sh intead
> docs: fix link to homepage

- Makefile
- cmd/glasskube/cmd/configure.go
- cmd/glasskube/cmd/describe.go
- cmd/glasskube/cmd/install.go
- internal/manifestvalues/cli/configure.go
- internal/manifestvalues/flags/flags.go
- internal/manifestvalues/flags/flags_suite_test.go
- internal/manifestvalues/flags/flags_test.go
- internal/manifestvalues/string.go
- internal/manifestvalues/validate.go
- internal/maputils/keys.go
- internal/web/server.go
- pkg/client/builder.go
- pkg/install/install.go
- website/docs/04_design/package-config.md
- website/docs/index.md
Closes #120 
Closes #119 
This PR adds the following features:
- Interactive value configuration during package installation
- Non-interactive value configuration during package installation
- A new subcommand `glasskube configure` for interactive and non-interactive value configuration of existing packages.
> feat(cli): add package configuration

- internal/web/server.go
> fix(ui): take configured values into account at installation

- .goreleaser.yaml
This already exists for the CLI but it makes sense to have it for the operator as well.
> build: add ldflags for operator

- .github/workflows/build.yaml
- .github/workflows/release.yaml
- Dockerfile
- go.mod
Fixes #266
We use this PR to check compatibility with the new Go version v1.22
> chore: update golang version to v1.22

- CONTRIBUTING.md
> docs: update go version to 1.22

- internal/telemetry/client.go
- internal/telemetry/properties/builder.go
> fix: avoid client rate limiting

- website/src/data/packages.tsx
- website/src/pages/packages/_components/PackageCard/styles.module.css
- website/src/pages/packages/index.tsx
- unify logo size
- always use white background
logos are hosted here: https://github.com/glasskube/glasskube/discussions/516
> docs(website): unify package logos from GitHub discussion

- .goreleaser.yaml
> build: fix copyright file location (#531)

- internal/clientutils/resources.go
Closes https://github.com/glasskube/glasskube/issues/524
HTTP errors handled when calling glasskube bootstrap
> HTTP errors handled correctly when calling glasskube bootstrap

- internal/controller/labels/labels.go
- internal/controller/owners/owners.go
- internal/controller/package_controller.go
- internal/manifest/helm/flux/adapter.go
- internal/manifest/plain/adapter.go
> fix(package-operator): do not set owner reference on existing resources

- internal/web/templates.go
- internal/web/templates/pages/package.html
> feat(ui): sort package versions descending (#308)

- README.md
Update readme file so that the messaging reflects the beta launch of Glasskube
> chore(main): update readme to reflect beta launch

- cmd/package-operator/main.go
- internal/telemetry/operator.go
- internal/telemetry/properties/builder.go
- internal/web/components/pkg_config_input/controller.go
> fix: avoid boolean parsing error

- internal/web/server.go
- internal/web/templates/layout/base.html
Closes https://github.com/glasskube/glasskube/issues/232
Added footer to the GUI with glasskube client and operator/cluster version.
> Added footer to the GUI with glasskube version

- website/docs/04_design/telemetry.md
Updated the telemetry page which just has a placeholder section until now
> docs(website): updated the telemetry page

- cmd/glasskube/cmd/update.go
Closes #462 
Fixes #462 
This PR add a new feature of auto completing the version for the update package command. 
Here I have added a new function for the completion of the available version. I have used the `describe.DescribePackage` function to identify the current version of the package installed.
> feat(cli): cli version completion

- internal/web/server.go
- internal/web/templates/layout/base.html
> fix(ui): introduce cache busting

- website/src/pages/roadmap.md
This road shouldn't become outdated as quickly as the old version.
> docs(website): updated roadmap to a more general approach

- website/package-lock.json
- website/package.json
- website/src/components/GiscusComponent.tsx
- website/src/theme/BlogPostItem/index.tsx
> docs(website): add giscus for blog post comments

- esbuild.mjs
- internal/telemetry/client.go
- internal/web/server.go
- internal/web/templates.go
- internal/web/templates/components/pkg-detail-header.html
- internal/web/templates/layout/base.html
- internal/web/templates/pages/discussion.html
- internal/web/templates/pages/package.html
- package-lock.json
- package.json
- web/custom.js
- web/index.js
Ref #207
This PR introduces a new discussion page on for each package, showing the giscus component.
> feat(ui): integrate giscus for package feedback (#207)

- website/blog/2024-05-02-kubectl-post/index.mdx
- website/guides/01_cert-manager.mdx
- website/guides/02_ingress-nginx.mdx
- website/guides/03_git-guide.mdx
- website/guides/04_kubectl-guide.mdx
- website/sidebar-guides.ts
- website/src/components/GiscusWrapper.tsx
- website/src/theme/BlogPostItem/index.tsx
> docs(website): kubectl guide

- internal/clientutils/resources.go
- internal/httperror/error.go
- internal/releaseinfo/releaseinfo.go
- internal/repo/client/defaultclient.go
- pkg/bootstrap/bootstrap.go
Closes https://github.com/glasskube/glasskube/issues/491
When there is network timeout or the device is offline while using glasskube bootstrap appropriate error will be printed in the terminal.
> refactor: added proper error handling for network related errors

- website/guides/04_kubectl-guide.mdx
Update the watch vs -w section
> docs(website): update the watch vs -w section

- website/docs/04_design/package-config.md
Fix spelling mistake in package-config.md
> Fix spelling mistake in package-config.md

- web/custom.js
> chore(ui): remove unnecessary console.log

- internal/web/server.go
- internal/web/templates/layout/base.html
> error handling fixes

- website/src/data/packages.tsx
- website/src/pages/packages/_components/PackageCard/styles.module.css
* add quickwit
* promote cnpg to available
* minor CSS fixes
> docs(website): update packages

- website/guides/05_rabbitmq.mdx
- website/sidebar-guides.ts
> docs(website): added rabbitmq guide

- .github/workflows/release.yaml
`google-github-actions/release-please-action` is deprecated
https://github.com/google-github-actions/release-please-action?tab=readme-ov-file#migration
> ci: migrate to googleapis/release-please-action

- internal/web/components/pkg_config_input/controller.go
- internal/web/server.go
- internal/web/templates.go
- internal/web/templates/components/pkg-config-input.html
- internal/web/templates/pages/package.html
> feat(ui): repository selection for package installation

- internal/web/server.go
- internal/web/templates.go
- internal/web/templates/layout/base.html
- internal/web/templates/pages/settings.html
> feat(ui): add settings page with list of repositories

- internal/constants/constants.go
- internal/telemetry/operator.go
- internal/telemetry/properties/builder.go
- internal/telemetry/properties/properties.go
- pkg/bootstrap/bootstrap.go
> chore: telemetry for repositories

- CONTRIBUTING.md
Closes # 
Added dependencies installation command to CONTRIBUTING.md
> docs: added dependencies installation to CONTRIBUTING.md

- website/blog/2024-05-20-devops/index.mdx
Added the DevOps blog post (without Gifs) to be published on Monday 20th May
> docs(website): added devops blogpost

- website/blog/2024-05-20-devops/index.mdx
- website/guides/01_cert-manager.mdx
- website/guides/02_ingress-nginx.mdx
- website/guides/03_git-guide.mdx
- website/guides/04_kubectl-guide.mdx
- website/guides/05_rabbitmq.mdx
- website/src/components/GiscusWrapper.tsx
> docs(website): fix giscus integration for guides

- api/v1alpha1/packagerepository_types.go
- cmd/glasskube/cmd/repo_add.go
- pkg/bootstrap/bootstrap.go
> add default support

- pkg/bootstrap/bootstrap.go
> fix: set correct API version to make bootstrap work

- internal/util/error.go
- internal/web/components/pkg_config_input/controller.go
- internal/web/server.go
- internal/web/templates/components/pkg-config-input.html
- internal/web/templates/pages/package.html
> feat(ui): show broken config references (#496)

- internal/web/server.go
Closes #684
In some cases the server would not choose the correct repository when initially navigating to the details page of a package. With this change, the server uses one the package is available from, preferring the default repository if possible.
> fix(ui): use correct repository on details page (#684)

- cmd/glasskube/cmd/configure.go
- cmd/glasskube/cmd/list.go
- cmd/glasskube/cmd/output_options.go
> Added --output support for glasskube configure

- website/docs/03_components/03_package-repository.md
- website/docs/index.md
> docs: include missing changes for multi-repo support

- internal/web/server.go
> fix(ui): support cloud links in bootstrap/kubeconfig pages

- internal/web/components/datalist/controller.go
- internal/web/components/pkg_config_input/controller.go
- internal/web/configurationvalues.go
- internal/web/server.go
- internal/web/templates.go
- internal/web/templates/components/datalist.html
- internal/web/templates/components/pkg-config-input.html
- internal/web/templates/pages/package.html
> feat(ui): autocomplete for reference inputs (#495)

- api/v1alpha1/packagerepository_types.go
- internal/giscus/client.go
- internal/telemetry/properties/properties.go
- internal/web/discussions.go
- internal/web/server.go
- internal/web/templates.go
- internal/web/templates/components/discussion-badge.html
- internal/web/templates/components/pkg-detail-header.html
- internal/web/templates/pages/discussion.html
> feat(ui): show reaction count on package detail page (#207)

- cmd/glasskube/cmd/install.go
> --output support for glasskube install 

- cmd/glasskube/cmd/bootstrap.go
Closes #719
Now the bootstrap command will ask for user confirmation if they want to use the current context and also they can omit the process with `--yes` flag
> feat(cli): Now bootstrap command will ask for user confirmation. (#719)

- README.md
> docs: add Go Reference and Go Report card badges

- internal/dependency/manager.go
- internal/dependency/manager_test.go
With this PR, the dependency validator checks whether a dependency error was actually introduced by the action it is validating. This is necessary because we currently do not support packages with more than one dependency, since that would lead to the following infinite loop:
1. try to install dep A --> error dep B is missing
2. try to install dep B --> error dep A is missing
3. repeat
> fix: add checking if error is new in dependency validation

- internal/web/server.go
- internal/web/templates.go
- internal/web/templates/components/pkg-config-advanced.html
- internal/web/templates/pages/package.html
- internal/web/templates/pages/settings.html
- web/custom.js
> feat(ui): add support for advanced options (#716)

- internal/controller/package_controller.go
This PR fixes the following error:
```
> go run -race ./cmd/glasskube install keptn --yes --non-interactive --version v2.0.0+1
Summary:
* The following packages will be installed in your cluster (minikube):
1. keptn (version v2.0.0+1)
2. cert-manager (version v1.14.5+1)
* Automatic updates will be not enabled
⣻ Installing keptn...  [0s] ❌ keptn installation has status Failed, reason: InstallationFailed
Message: failed to get required package cert-manager: Package.packages.glasskube.dev "cert-manager" not found
```
The status is set to failed incorrectly, because the package operator has the responsibility to create the dependency. 
This error occurs because the package-controller uses the controller-runtime client which uses a cache for read operations. This means that a Get operation …
> fix(package-operator): mark dependency as "waitingFor" if not found

- internal/web/templates.go
- internal/web/templates/pages/settings.html
Closes #733 
I added a simple bootstrap badge to indicate default repository on the website
> feat(website): add badge to indicate default repository (#733)

- CONTRIBUTING.md
> docs: update local repo section

- CONTRIBUTING.md
- README.md
- website/src/data/packages.tsx
- improve readme
- add more packages
- update contributing guide
please rebase and don't squash merge as want to reference the single contributing commit
> docs: various docs improvements

- cmd/glasskube/cmd/describe.go
Closes #655 
Fixes #655 
Continues #673 
This PR adds the feature of getting the output in the `JSON` and `YAML` formats.
- Output in YAML format:
```
AutoUpdate: Disabled
Configuration: {}
Dependencies: []
Entrypoints:
- Local: http://localhost:3000/
Name: ui
Remote: cyclops-ui:3000
LongDescription: |-
Welcome to Cyclops, a powerful user interface for managing and interacting with Kubernetes clusters.
Cyclops is designed to simplify the management of containerized applications on Kubernetes,
providing an intuitive and user-friendly experience for developers, system administrators, and DevOps professionals.
Divide the responsibility between your infrastructure and your developer teams so everyone can play to their strengths.
Automate your processes and shrink the window for deployment …
```
> feat(cli): add `--output` flag to `glasskube describe`

- internal/controller/owners/owners.go
This PR changes the `SetOwner` utility to take advantage of the newly added `WithBlockOwnerDeletion` option of the controller-runtime utils.
Also, fixes some formatting errors.
> chore(package-operator): use WithBlockOwnerDeletion from controllerutil

- website/src/theme/cloud-banner.js
> fix(website): avoid full page crash

- internal/web/templates/pages/settings.html
Closes #751
Adds an additional text representing repository status when hovering with the mouse over the circle next to any repository on the settings page.
> feat(ui): show repository status on settings page

- CONTRIBUTING.md
Closes #778
fix broken `pull request template` URL.
Please check from the following link.
https://github.com/mahiro72/glasskube/blob/mahiro72/fix-docs-broken-url-pull-request-tmplate/CONTRIBUTING.md#keeping-your-fork-up-to-date-
> docs: fix broken pull request template url

- CONTRIBUTING.md
We simplified our workflow. This PR makes our contributing guide reflect those changes.
> docs: update contributing guide with updated PR workflow

- CONTRIBUTING.md
This PR corrects a documentation mistake from by previous re-write of the git part of our contribution guide.
> docs: correction in contributing.md

- internal/web/templates/layout/base.html
> feat(ui): add discord link in glasskube footer ui

- website/package-lock.json
Fixes a vulnerability: https://github.com/advisories/GHSA-3h5v-q93c-6h6q
> chore(deps): update website dependency ws to v8.17.1

- cmd/glasskube/cmd/purge.go
- pkg/bootstrap/bootstrap.go
- pkg/purge/purge.go
- pkg/statuswriter/spinner.go
> feat(cli): add `purge` command to remove installation from a cluster

- cmd/glasskube/cmd/uninstall.go
- pkg/uninstall/uninstall.go
> feat(cli): add uninstalling namespaced packages

- internal/dependency/manager.go
- internal/dependency/manager_test.go
- internal/webhook/package_validator_test.go
> fix: temporarily disable considering packages in dependency manager

- website/docs/02_getting-started/03_upgrading.mdx
Ref #803
Adds a new "upgrading" page to the "Getting started" section of the documentation. This page has a section dedicated to breaking changes.
> docs: add upgrading guide

- README.md
Replace static image with interactive GIF in README
> docs: exchange static image with gif

- website/docs/05_comparisons/02_timoni.md
Spelling mistake, from "(co-)singing" to "(co-)signing"
Closes #
> docs(website): fix typo

- pkg/open/open.go
> fix(open): fix typo in service name candidate

- website/blog/2024-03-22-release-0.1.0/index.mdx
- website/blog/2024-04-26-beta-launch-blog/index.mdx
- website/guides/04_kubectl-guide.mdx
Closes #884 
Replaced all normal youtube embed links with youtube-nocookie links
> docs(website): change YouTube embeds to use youtube-nocookie

- cmd/glasskube/cmd/configure.go
- cmd/glasskube/cmd/kind_options.go
- cmd/glasskube/cmd/open.go
- internal/dependency/manager.go
- internal/dependency/manager_test.go
- internal/webhook/package_validator_test.go
> chore(cli): enable `--kind`, `--namespace` flags

- cmd/glasskube/cmd/auto-update.go
> feat: add namespace support for enable/disable auto-update

- cmd/glasskube/cmd/install.go
- cmd/glasskube/cmd/namespace_options.go
- internal/controller/ctrlpkg/util.go
- internal/web/server.go
- pkg/client/builder.go
- pkg/install/install.go
- pkg/uninstall/uninstall.go
> feat(cli): add installing namespace-scoped packages

- cmd/glasskube/cmd/auto-update.go
- cmd/glasskube/cmd/update.go
- internal/web/server.go
- pkg/update/getter.go
- pkg/update/update.go
> feat(cli): add support for updating namespace-scoped packages

- cmd/glasskube/cmd/auto-update.go
> feat(cli): add support for auto-updating namespace-scoped packages

- website/docs/index.md
> docs: document purge command

- cmd/glasskube/cmd/bootstrap.go
- pkg/bootstrap/bootstrap.go
- pkg/bootstrap/type.go
Closes #725
Fixes #725
In this PR I have added the `--dry-run` to the `glasskube bootstrap` command
> feat(cli): add --dry-run to bootstrap command

- internal/web/discussions.go
Closes https://github.com/glasskube/glasskube/issues/905
auto update value was not passed to the discussion page whereas it was passed to package detail page, hence the bug.
> fix(ui): autoupdate label for discussion page

- config/autoupdater/cronjob.yaml
- config/autoupdater/kustomization.yaml
- config/autoupdater/rbac.yaml
- config/autoupdater/serviceaccount.yaml
- hack/generate-manifests.sh
This PR adds manifests for a "auto-update" cronjob.
This is a preparation for the auto update package
> feat(deploy): add autoupdate manifest

- internal/telemetry/client.go
- internal/web/pathredactor.go
- internal/web/pathredactor_test.go
- internal/web/server.go
- internal/web/web_suite_test.go
> chore(ui): telemetry should exclude certain paths

- pkg/list/lister.go
- pkg/list/result.go
> fix(cli): `--outdated` and `--installed` for listing packages

- internal/web/packagedetail.go
> fix(ui): also show validation errors in package config form

- internal/web/templates.go
> fix(ui): add blockquote styling in markdown

- website/blog/2024-07-02-quickwit/index.mdx
- website/guides/06_quickwit.mdx
- website/sidebar-guides.ts
Added the Quickwit blog and guide
> docs(website): quickwit assets

- cmd/glasskube/cmd/auto-update.go
See #901
The previous PR that was supposed to do this (#901) contained an error…
> fix(cli): do not require bootstrap for `glasskube auto-update`

- internal/web/server.go
- internal/web/templates/components/clpkg-overview-btn.html
- internal/web/templates/pages/packages.html
> feat(ui): open and update buttons for namespaced packages

- website/docs/04_design/telemetry.md
> docs(website): clarify telemetry instructions

- website/docs/02_getting-started/02_bootstrap.mdx
> docs: document which flux components are required in which version

- website/docs/02_getting-started/02_bootstrap.mdx
Closes #948  
See issue discussion
> docs: add common issues section on bootstrap page

- internal/web/templates/components/pkg-config-input.html
Closes https://github.com/glasskube/glasskube/issues/734
Mardownify the package value description
> feat(ui): support markdown in package value description

- internal/manifest/helm/flux/adapter.go
This one kind of slipped through in https://github.com/glasskube/glasskube/pull/622
> chore(package-operator): update flux source-controller api version to v1

- internal/contenttype/mediatype.go
> fix: allow additional yaml content types

- website/blog/2023-12-14-5-helm-shortcomings/index.mdx
- website/blog/authors.yml
Migrating https://glasskube.eu/en/r/knowledge/5-helm-shortcomings/ to our new website.
> docs(website): migrate 5 helm shortcomings blog to glasskube.dev

- internal/web/templates/components/pkg-detail-header.html
Closes #898 
Added status badge and alert box below header whenever the status goes failed to show the message.
> feat(ui): status message on package details page

- website/guides/07_kube-prom-stack.mdx
- website/sidebar-guides.ts
Added Kube-prometheus-stack guide
> docs(website): added kube-prometheus-stack guide

- website/guides/08_package-creation.mdx
- website/sidebar-guides.ts
> docs(website): added new package creation guide

- website/docusaurus.config.ts
> docs(website): call for help in GNP design

- internal/web/templates/pages/package.html
The link was outdated since #803
> fix(ui): broken link to required package

- cmd/glasskube/cmd/serve.go
- internal/web/server.go
Closes #993  
Adds a new flag to the `serve` command: `--host`
I also took the opportunity and cleaned up the "use different port" feature a little. 
I discovered a potential bug related to the cache verifier: While the cli is waiting for user input after the question "Should glasskube use a different port?", the cache verifier already starts printing warnings and eventually the command is stopped. This behavior already exists in current `main`. To reproduce (works 100%): Run `glasskube serve` in two separate terminals.
> feat(cli): add `--host` flag for `serve` to change the hostname for the listener

- website/src/css/custom.css
Closes #880
- Fixes CSS Minimizer Warnings in Website during `npm run build`
> chore(website): css minimizer warnings in website build

- cmd/glasskube/cmd/install.go
> feat(cli): add `--show-all-metadata` flag for `install` command

- website/docusaurus.config.ts
use a custom telemetry url for the website
> chore: use glasskube telemetry url

- website/docusaurus.config.ts
- website/eslint.config.mjs
- website/package-lock.json
- website/src/components/buttons/ContactSalesButton.tsx
- website/src/components/buttons/CustomGitHubButton.tsx
- website/src/components/buttons/DemoButton.tsx
- website/src/components/buttons/SignupForWaitlistButton.tsx
- website/src/components/buttons/TalkToFoundersButton.tsx
- website/src/data/packages.ts
- website/src/data/pricing.ts
- website/src/pages/packages/index.tsx
- website/src/pages/pricing/_components/PricingComponent/index.tsx
- website/src/pages/pricing/_components/PricingComponent/styles.module.css
- website/src/pages/pricing/_components/PricingFaqComponent/index.tsx
- website/src/pages/pricing/_components/PricingFaqComponent/styles.module.css
- website/src/pages/pricing/index.tsx
- website/src/theme/NavbarItem/NavbarWrapper/index.tsx
- website/static/robots.txt
> feat(website): add pricing page

- website/src/components/Home/index.tsx
- website/src/components/buttons/ContactSalesButton.tsx
- website/src/components/buttons/DemoButton.tsx
- website/src/components/buttons/SignupForWaitlistButton.tsx
- website/src/components/buttons/TalkToFoundersButton.tsx
- website/src/pages/pricing/_components/PricingComponent/index.tsx
- website/src/pages/pricing/_components/PricingFaqComponent/index.tsx
> docs(website): improve pricing page light mode

- cmd/glasskube/cmd/auto-update.go
- cmd/glasskube/cmd/update.go
- internal/web/server.go
- pkg/update/update.go
Closes #660 
Fixes #660 
This PR adds the `--dry-run` tags to the update command.
> feat(cli): add --dry-run to update command

- cmd/glasskube/cmd/open.go
- internal/web/server.go
- pkg/open/open.go
> feat: open entrypoint with custom hostname

- website/.prettierrc.mjs
- website/custom-blog-plugin.js
- website/sidebar-guides.ts
- website/sidebars.ts
- website/src/components/GiscusWrapper.tsx
- website/src/components/Home/index.tsx
- website/src/components/HomepageBlogs/index.tsx
- website/src/components/HomepageFeatures/index.tsx
- website/src/components/HomepageScreenshots/index.tsx
- website/src/components/buttons/SignupForWaitlistButton.tsx
- website/src/data/packages.ts
- website/src/data/pricing.ts
- website/src/pages/packages/_components/PackageCard/index.tsx
- website/src/pages/packages/_components/PackageFilterToggle/index.tsx
- website/src/pages/packages/_components/PackageTagSelect/index.tsx
- website/src/pages/packages/index.tsx
- website/src/theme/NavbarItem/NavbarWrapper/index.tsx
This PR fixes _most_ eslint warnings on the website. One error remains, but I am not sure how to best resolve it.
Unrelated to this PR, but I noticed the following warning during build:
```
Exhaustive list of all broken anchors found:
- Broken anchor on source page path = /pricing/:
-> linking to #free-trial (resolved as: /pricing/#free-trial)
-> linking to #free-tier (resolved as: /pricing/#free-tier)
-> linking to #invoice (resolved as: /pricing/#invoice)
-> linking to #currency (resolved as: /pricing/#currency)
-> linking to #gitops (resolved as: /pricing/#gitops)
-> linking to #paas (resolved as: /pricing/#paas)
-> linking to #kubernetes (resolved as: /pricing/#kubernetes)
```
Are we aware of this? Or is it a false positive?
> chore(website): fix eslint errors and warnings

- website/blog/2024-08-07-gitops-template/index.mdx
> docs(website): added initial gitops template blog

- website/docs/02_getting-started/02_bootstrap.mdx
- website/docs/04_design/gitops.md
> docs: gitops integration

- CONTRIBUTING.md
No issue
Adds a section to the contributing guide on how to create a new validating webhook.
> docs(contrib): add guide for creating a new validating webhook

- cmd/glasskube/cmd/uninstall.go
- internal/web/server.go
- pkg/uninstall/uninstall.go
Closes #1061 
Fixes #1061 
This PR adds the `DryRun` options to the uninstall command
> feat(cli): add --dry-run to uninstall command

- website/docs/index.md
This PR adds missing documentation for the auto-update CLI command.
> docs: add documentation for the auto-update command

- internal/manifestvalues/resolver.go
- internal/manifestvalues/resolver_test.go
> fix: remove base64 decoding of secret values in config resolver

- website/docs/04_integration/gitops.md
- website/docs/04_integration/renovate.md
Add a Renovate example
depends on https://github.com/glasskube/gitops-template/pull/18
> docs(website): add Renovate example

- internal/cliutils/versionutil.go
> fix(cli): show a different operator version warning in dev mode

- pkg/bootstrap/bootstrap.go
> fix: retry on certificate errors during bootstrap

- cmd/glasskube/cmd/bootstrap_git.go
- pkg/bootstrap/bootstrap.go
- pkg/open/open.go
Closes #1173 
Ref https://github.com/glasskube/gitops-template/issues/15
* Added support for private GitHub repositories. Repo credentials are passed via `--username` and `--token` arguments. 
* Made the command block until argo-cd is actually openable, and print the initial admin password. 
https://github.com/glasskube/gitops-template/pull/17
> feat(cli): improve gitops bootstrap support

- internal/dependency/graph/graph.go
- internal/web/templates/components/pkg-uninstall-modal.html
> chore: output of package dependencies and components

- website/blog/2024-02-01-technical-preview/index.mdx
- website/blog/2024-02-08-cncf-landscape/index.mdx
- website/blog/2024-02-12-open-command/index.mdx
- website/blog/2024-02-14-kubernetes-frontends/index.mdx
- website/blog/2024-02-27-release-package-updates/index.mdx
- website/blog/2024-03-22-release-0.1.0/index.mdx
- website/blog/2024-03-26-discord-setup/index.mdx
- website/blog/2024-04-04-contributor-guidelines/index.mdx
Added missing images to the blog posts that didn't have one.
> docs(website): added image thumbnails to blog which are missing them

- internal/dependency/manager.go
I tested this with the following simple local package that "simulates" trieve:
```
name: trieve-local
iconUrl: https://avatars.githubusercontent.com/u/47359
shortDescription: Trieve
longDescription: |
Test
defaultNamespace: default
scope: Namespaced
dependencies:
- name: clickhouse-operator
- name: cloudnative-pg
components:
- name: qdrant
- name: redis
- name: tika
- name: keycloak-operator
manifests:
- url: ./service.yaml
```
and a random `service.yaml` (copied from tika, because I think a package without anything doesn't work?) like this:
```
kind: Service
apiVersion: v1
metadata:
name: trieve
spec:
ports:
- port: 9998
name: tika
selector:
app: tika
```
> fix: package manifest fallback strategy in dependency manager

- internal/web/server.go
- internal/web/templates.go
- internal/web/templates/pages/repository.html
- internal/web/templates/pages/settings.html
Closes #861 , #860
Adding a separate page linked to setting which allows to edit the repositories. Can edit url and default status of the repo config file.
Editing the Url for the repo:
https://github.com/user-attachments/assets/402569bf-8f5b-47ec-942e-b5ac656258f5
Showing error if not able to edit:
https://github.com/user-attachments/assets/ce07dc24-26c7-47aa-a079-0639a0d610ab
> feat(ui): add editing of package repositories

- internal/manifest/plain/adapter.go
> feat(package-operator): check readiness of deployments and stateful sets

- README.md
Added helloGitHub badge to readme, spurred by this [discussion](https://github.com/glasskube/glasskube/discussions/1175).
> docs(website): added helloGitHub badge to readme

- .goreleaser.yaml
Closes # [1191](https://github.com/glasskube/glasskube/issues/1191)
add the three homebrew shell completion functions to the goreleaser.yaml brew install block
> build(cli): add completions on brew install

- website/blog/2024-08-07-gitops-template/index.mdx
- website/blog/2024-09-09-launch-week-2/index.mdx
Added truncation marker to blog post and gitops template post
> docs(website): added truncation marker to template and launch post

- .goreleaser.yaml
> fix(cli): fix typo in homebrew completion command

- website/docusaurus.config.ts
Updated site banner to announce the launch week
> docs(website): change the site banner

- website/blog/2024-09-09-launch-week-2/index.mdx
> docs(website): improve launch week wording

- website/blog/2024-09-09-launch-week-2/index.mdx
> docs(website): added link to package scope section of the launch blog

- internal/web/components/datalist/controller.go
- internal/web/packagedetail.go
- internal/web/server.go
- internal/web/templates/pages/package.html
Closes #1149
Unlike said in the issue description, I opted for a more minimal solution (label "will be created if necessary") for now, in favor of the "proper" refactoring of the page in #1167 – I think in this follow-up issue we can also take a look how some more client-side interactivity could be achieved. 
Nevertheless, I also added the namespace datalist to the input field, since we have the data anyway and might as well show what's available already.
> feat(ui): create namespace at installation

- internal/web/server.go
Followup of #1237, where this bug was introduced. 
Ref #976
> fix(ui): error installing clusterpackage

- website/src/components/buttons/SignupForWaitlistButton.tsx
> docs(website): rename cta

- website/docusaurus.config.ts
- website/src/components/HomepageFeatures/index.tsx
- website/src/components/buttons/ContactSalesButton.tsx
- website/src/components/buttons/SignupForWaitlistButton.tsx
- website/src/pages/pricing/_components/PricingComponent/index.tsx
- website/src/pages/products/package-manager/index.tsx
- website/src/theme/NavbarItem/NavbarWrapper/styles.module.css
> docs(website): improve wording

- internal/adapter/types.go
- internal/dependency/default_repo_adapter.go
- internal/dependency/manager.go
> fix: dependency manager uses given repository if known

- cmd/glasskube/cmd/describe.go
- internal/web/templates.go
- internal/web/templates/pages/package.html
Closes #1178 
Now showing package components on UI + CLI. Additonally, I improved the recent improvement of the package detail page (better looking form) and I removed the "Package Details" and "Package Dependencies" section headings (debatable, but I thought it looked a bit bulky, and it kind of works without headings too?).
> feat: show package components

- internal/dependency/default_repo_adapter.go
- internal/dependency/manager.go
- internal/repo/client/metaclient.go
> fix: avoid dependency errors during uninstallation

- website/src/pages/pricing/_components/PricingComponent/index.tsx
There was a typo in the pricing page: "Never maintain a Helm charts every again".
Modified it to: "Never maintain Helm charts ever again"
> docs(website): fix typo in website

- cmd/glasskube/cmd/install.go
- internal/clientutils/autoupdate.go
- internal/web/discussions.go
- internal/web/packagedetail.go
- internal/web/sse/broadcaster.go
- internal/web/templates.go
- internal/web/templates/components/pkg-detail-header.html
- internal/web/templates/pages/package.html
> feat: make auto update changeable on UI and show hint

- internal/controller/common.go
> fix(package-operator): also set `ownedPackages` when dependencies unresolved

- website/package-lock.json
- website/package.json
This PR updates the TrieveSiteSearchComponent to the latest version.
Change Log:
- Removed dependencies to reduce js bundle size by 300 KB 📦
- Added breadcrumbs in search items to make the results clearer 🔍
- UI refresh, removed the bottom outside border for a more sleek look ✨ 
Before:
After:
> feat(website): updates Trieve search theme to version 0.1.17

- website/blog/2024-11-07-postgres-on-kubernetes/index.mdx
Part 1 of 3 blog posts on the topics on PostgreSQL on Kubernetes.
> docs(website): initial commit of the postgres on k8s blog post

- website/blog/2024-11-11-kubeflow-setup/index.mdx
> docs(website): add kubeflow header image to blog post

- website/blog/2024-11-11-kubeflow-setup/index.mdx
> docs(website): add second cta for kubeflow post

- website/blog/2024-11-25-saas-vs-byoc-on-prem/index.mdx
> docs(website): fix broken link

- website/src/components/HomepageBlogs/index.tsx
- website/src/components/HomepageProducts/index.tsx
- website/src/components/cta/DefaultCTA/defaultCTA.tsx
- website/src/data/pricing.ts
> docs(website): made some typo fixes

- website/src/pages/pricing/_components/PricingComponent/index.tsx
> docs(webiste): fix link

- website/glossary/14_isv.mdx
- website/sidebar-glossary.ts
> docs(website): glossary isv

- website/docusaurus.config.ts
- website/src/components/Home/index.tsx
- website/src/components/HomepageProducts/index.tsx
- website/src/components/buttons/DemoButton.tsx
- website/src/components/buttons/SignupForWaitlistButton.tsx
- website/src/components/cta/CustomCTA/customCTA.tsx
- website/src/pages/contact/ContactForm/index.module.css
- website/src/pages/contact/ContactForm/index.tsx
- website/src/pages/contact/index.tsx
- website/src/pages/contact/styles.module.css
- website/src/pages/pricing/_components/PricingComponent/index.tsx
- website/src/theme/BlogSidebar/index.tsx
- website/src/theme/NavbarItem/NavbarWrapper/index.tsx
- website/static/robots.txt
> docs(website): add contact form

- website/src/pages/contact/ContactForm/index.tsx
> docs(website): fix company name input type
